### ISSUE TITLE
Untested FreeRTOS function when running thread.list()

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#101]
When listing all the threads I'm getting the error: "Untested FreeRTOS function uxTaskGetSystemState" and the Chip resets.

I was trying to figure out why the Watchdog timer issue keeps coming back (not fed).

**Comment by thunderWhitecat** [comment]
Check that you have disabled the setting Component Config -> FreeRTOS -> Halt when a SMP-untested function when executing "make menuconfig" from the command line.

If this setting is enabled, disable it, build, and try again.
