### ISSUE TITLE
mqtt module not working as described by wiki

### ISSUE THREAD

**Issue by aresrepair** [whitecatboard/Lua-RTOS-ESP32#105]
![image](https://user-images.githubusercontent.com/4078184/33895518-bfb3cce4-df71-11e7-9c0c-b0231b9ff680.png)

**Comment by thunderWhitecat** [comment]
Hi @aresrepair,

mqtt.client has 4 arguments as described in the wiki (https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/MQTT-module#client--mqttclientclientid-host-port-secure).

**Comment by aresrepair** [comment]
Hi jolivepetrus,
![image](https://user-images.githubusercontent.com/4078184/33896030-dfa1d4b4-df72-11e7-9f40-0557406429c9.png)
I use 4 arguments too
excuse me for bad example

**Comment by aresrepair** [comment]
it works if I have 6 args:
![image](https://user-images.githubusercontent.com/4078184/33897566-d87c2f46-df76-11e7-8e6b-70570065a925.png)

**Comment by thunderWhitecat** [comment]
Please, try to update to last Lua RTOS version. Since commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/d89202db5b8760147f9297cc8b5a7c8ea826da83 Lua RTOS has backward compatibility with the API described in the wiki. Arguments from argument 5 will be described soon.

**Comment by aresrepair** [comment]
Thank you @jolivepetrus 
good work!
all works fine!
