### ISSUE TITLE
W5500 ethernet support ?

### ISSUE THREAD

**Issue by psykokwak-com** [whitecatboard/Lua-RTOS-ESP32#107]
Hi,
I see that ethernet support is provided by the ENC28J60 chip.
But do you think it is possible to add the W5500 one ? 
Thanks.

**Comment by thunderWhitecat** [comment]
It should be feasible,

... but RMII support is added since a few weeks ago ....

I have to update the wiki.

Best regards,

Jaume

**Comment by psykokwak-com** [comment]
RMII use too much IO.
The W5500 like the ENC28J60 use SPI which can be shared with other SPI devices.

Best regards,

**Comment by thunderWhitecat** [comment]
It would be great to add support for this hardware in Lua RTOS, due to its lower price!
Can you develop this feature with our technical support?
