### ISSUE TITLE
undefined reference to `vfs_select'

### ISSUE THREAD

**Issue by aresrepair** [whitecatboard/Lua-RTOS-ESP32#109]
Hi!
After last git pull
I have next error:
![image](https://user-images.githubusercontent.com/4078184/34906216-ccbd91ce-f879-11e7-9f70-554a759956a4.png)

what happened?

**Comment by thunderWhitecat** [comment]
sdkconfig file?

**Comment by aresrepair** [comment]
[sdkconfig.zip](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/1628534/sdkconfig.zip)

**Comment by thunderWhitecat** [comment]
Hi @aresrepair,

I can't reproduce this issue with your sdkconfig file.

Please, be sure that you have Lua RTOS and esp-idf upgraded to the last version and try again.

You can upgrade from the Lua RTOS folder as follows:

$ make upgrade-idf

**Comment by aresrepair** [comment]
Hi @jolivepetrus,
It's solution, thank you
