### ISSUE TITLE
minor issue in mqtt.subscribe

### ISSUE THREAD

**Issue by loboris** [whitecatboard/Lua-RTOS-ESP32#11]
Mqtt subscribe causes the panic:
```
/ > mq:subscribe("test",0,mqmsg)
Guru Meditation Error of type LoadProhibited occurred on core  0. Exception was unhandled.
Register dump:
....
```
The source of the error is to small alocated memory for _topic_ string in **add_subs_callback** function.
It is necessary to change:
`    callback->topic = (char *)malloc(strlen(topic));`
to
`    callback->topic = (char *)malloc(strlen(topic)+1);`

With that change _subscribe_ function works as expected.

**Comment by thunderWhitecat** [comment]
Thanks for report this. This is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/8b02d923db97f185330ebfb170fa162bfc5fc56d.
