### ISSUE TITLE
project build error

### ISSUE THREAD

**Issue by mgrusik** [whitecatboard/Lua-RTOS-ESP32#114]
Tell me what could be the problem? Thank you!

C:/msys32/home/Alex/esp/Lua-RTOS-ESP32/components/http/httpsrv.c:1195:23: error: 'CPU_INITIALIZER' undeclared
C:/msys32/home/Alex/esp/Lua-RTOS-ESP32/components/http/httpsrv.c:1199:45: error: 'cpu_set_t' undeclared

**Comment by thunderWhitecat** [comment]
Hi, @mgrusik,

Please, build with last commit (https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/059b7b5714dce5dc72f6c3c062fee2ac2bbc0072). This should solve the issue.

**Comment by mgrusik** [comment]
Hi, @jolivepetrus !
did not help!

and it should be so?
_pthread.c
_pthread.h

**Comment by thunderWhitecat** [comment]
Can you send us the error? Screen capture, or something like that?

**Comment by mgrusik** [comment]
I yesterday updated the project and all the errors were gone, thank you! 
tell me how to load spiffs_image default

**Comment by thunderWhitecat** [comment]
To flash the default file system:

make flashfs

**Comment by mgrusik** [comment]
![error](https://user-images.githubusercontent.com/36403181/36255318-326147a4-1257-11e8-87f1-270a3e1e9753.png)

**Comment by thunderWhitecat** [comment]
I'm trying to solve this issue but I'm not using windows from years and years.
Building Lua RTOS, and any esp-idf program in windows is too slow.
15 minutes compiling and not finish yet, with antivirus disabled. Is it normal?.

**Comment by thunderWhitecat** [comment]
Hi @mgrusik,

Please, try with this commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/e86d50351ffb35cadd6372e29d98e9cb3cd7ef6a. It was some issues in building Lua RTOS on Windows.

In my setup environment works perfect.

make flash -> build and flash Lua RTOS
make flashfs -> build and flash default flash system

**Comment by gjongenelen** [comment]
I'm gonna join this topic because it's related to build errors. After the commit of tonight I'm getting build errors:
`Lua-RTOS-ESP32/components/compat/./gai_strerror.c:54:7: error: 'EAI_BADFLAGS' undeclared (first use in this function)`
This is with the latest LuaRTOS and esp-idf versions

**Comment by mgrusik** [comment]
hi, i have ~ 13 minutes compiled

**Comment by thunderWhitecat** [comment]
@gjongenelen,

Please, proceed as follows:

make clean
make upgrade-idf
make

**Comment by thunderWhitecat** [comment]
@mgrusik,

Have you test last commit?
All is right?

**Comment by mgrusik** [comment]
all right, thank you!
