### ISSUE TITLE
Why only SPI.master?

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#115]
Hello,

We need to hookup a device which operates in SPI.master mode. We cannot change this. Why is SPI.slave mode not allowed?

(https://github.com/espressif/esp-idf/issues/210 is closed already)

**Comment by the0ne** [comment]
@gjongenelen can you please verify if this issue does still exist?

in the spi.attach interface I can see that the second parameter is used to set whether the setup is done as master or not `is_master = luaL_checkinteger(L, 2) == 1`
also, in the [wiki](https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/SPI-Module) I can see that the second parameter is defined as 
> mode: SPI mode, can be either spi.MASTER or spi.SLAVE

please close this issue in case it's not open anymore. thanks!
