### ISSUE TITLE
net.wf mac address?

### ISSUE THREAD

**Issue by skitsanos** [whitecatboard/Lua-RTOS-ESP32#117]
Is there any way to get mac address from net.wf?

**Comment by thunderWhitecat** [comment]
Yes, of course,

Yo can use the net.stat function, that can return the network information into a table.

You have more information in the wiki:

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Net-Module#common-functions

**Comment by skitsanos** [comment]
Sorry for bothering again, but maybe im doing something wrong?

netstat=net.stat(true)

gives me:
attempt to index a boolean value

**Comment by skitsanos** [comment]
okay, found the issue. it the documentation that is needs to be updated

if you do
netstat = net.wf.stat(true)

then it returns table as expected...

**Comment by thunderWhitecat** [comment]
Hi @skitsanos,

There was a bug when calling net.stat(true). Commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/8788183c1d45eb38e282b13fd53d7720dc897c3f solves this bug.

The idea is that net.stat(true) returns the information of all available interfaces, while net.wf.stat(true) or net.en.stat(true) returns the information of the wifi and ethernet respectively.
