### ISSUE TITLE
Mqtt can't connect

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#118]
Hi,
When connecting to Mqtt it doesn't throw any errors. It just prints
```.MQTT�<{CLIENT_ID}{USERNAME}{PASSWORD}```
With the actual parameters, but omitted here. 

Resulting in the following error after +/- 10 secs:
Guru Meditation Error: Core 0 panic'ed (LoadProhibited)

This used to work before, don't know what happened that it doesn't work now.
Btw, Wifi is connected

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

Tested with last commit, last esp-idf, and last toolchain. Can't reproduce the issue with any secure setup: plain, secured, tls, ....

**Comment by thunderWhitecat** [comment]
Hi @gjongenelen,

Any progress in this issue? Can be closed?

**Comment by gjongenelen** [comment]
It turned out to be a corrupt system, completely wiping the ESP and reflashing it worked. Sorry for the inconvenience!
