### ISSUE TITLE
Curl default CA

### ISSUE THREAD

**Issue by max1220** [whitecatboard/Lua-RTOS-ESP32#122]
It seems that curl still ships with the ca-certificates.crt from some example code (The CA is the same as the CA from here: https://github.com/loboris/ESP32_curl_example).
This obviously isn't right.
I don't know what CA's to put in this file, but maybe letsencrypt as a default would be a good choice?

**Comment by the0ne** [comment]
@max1220 I may be wrong or missing something, but I don't see where this file would automatically be put onto the esp32 file-system. So if my understanding is correct, it's up to the developer to decide which file to place at /certs/ca-certificates.crt

@jolivepetrus should this be "moved" to e.g. /etc/certs/ca-certificates.crt by updating CURL_CA_BUNDLE in file components/curl/lib/curl_config.h ?

**Comment by max1220** [comment]
@TheOne What point is there in shipping a default CA from some example? As far as I can see, on Master, in components/curl/ if for loboris.ihostfull.com, and maybe used in some examples, but should definitely be replaced. (If not, the board would trust some random, home-generated CA, and I don't think that's the intention. Please correct me if I'm wrong)

**Comment by the0ne** [comment]
@max1220 as it's not included in the build, technically it's not being *shipped* in any way. if you have created a fork of the project or cloned it to your local storage, it should be safe if you want to delete the file there. If you want the file to be removed from the project, you could also create a [PR](https://github.com/whitecatboard/Lua-RTOS-ESP32/pulls).

**Comment by the0ne** [comment]
no answer - closing
