### ISSUE TITLE
wifi wpa2 enterprise

### ISSUE THREAD

**Issue by gmenier** [whitecatboard/Lua-RTOS-ESP32#123]
Hi,
Not really an issue : is there any kind of support in LuaRTOS for wpa2 enterprise ? It seems there is some related code (in the source). Has someone forked or tried something (with success :-) ) ?
(and btw thank you for the bug fixing)
G.

**Comment by oskarirauta** [comment]
esp-idf does seem to come with example for WPA2-EAP, so it **should** be possible.
+1 for this feature.

**Comment by the0ne** [comment]
Took me a day to _properly_ set up radius on my router and WEP2 Enterprise on a wifi-bridge inside that router network. Finally I can login to the WiFi with my Android phone using a client-certificate and username/password.

Implementation of driver and lua part is ready but there's issues in the esp32 idf it seems:
_wpa: Method private structure allocated failure_

**Comment by the0ne** [comment]
Implemented as e6799c58d6d2607023c1742d3cbaedd049b6fd57 and created PR #241

**Comment by the0ne** [comment]
@gmenier please test with a recent version
