### ISSUE TITLE
Bluetooth isn't sswitch off able

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#125]
Although I deactivated bluetooth in menuconfig, I get the following error message:

In file included from /home/fh/Lua-RTOS-ESP32/components/sys/drivers/bluetooth_hci.c:47:0:
/home/fh/Lua-RTOS-ESP32/components/sys/drivers/bluetooth.h:50:25: fatal error: esp_bt_defs.h: No such file or directory
compilation terminated.
/home/fh/esp/esp-idf/make/component_wrapper.mk:273: die Regel für Ziel „drivers/bluetooth_hci.o“ scheiterte
make[1]: *** [drivers/bluetooth_hci.o] Fehler 1
/home/fh/esp/esp-idf/make/project.mk:450: die Regel für Ziel „component-sys-build“ scheiterte
make: *** [component-sys-build] Fehler 2

Due to lack of memory (wifi, luasocket,TCP, ...), I want to disable bluetooth

**Comment by thunderWhitecat** [comment]
@lu1210, thanks for report this.

Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/0373d2a6f9810b0738be8211dd868f2434e1ccdf
