### ISSUE TITLE
rm directory error

### ISSUE THREAD

**Issue by disassembly** [whitecatboard/Lua-RTOS-ESP32#126]
First of all, thank you very much for the fantastic lua-rtos. I've just working it with esp32 for a while.
When I tried to login to the ssh server of lua-rtos without password, I make a directory under /, i.e. /.ssh, and then touch a file authorized_keys filled with my public key. It doesn't work though. After that I try to rm authorized_keys and then rm .ssh, It get an error:
.ssh: Directory not empty
The right way to rm .ssh directory should be:
mv .ssh ssh
followed with:
rm ssh
So I think there might be a small bug of rm command when dealing with special characters such as '.'.
Best wishes!

**Comment by the0ne** [comment]
i confirm that
`rm *ssh`
doesn't work as well.

the issue occurs in check_path() in spiffs.c
fixed with c4ae08e
