### ISSUE TITLE
make menuconfig;menu items are blocked

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#130]
menu items, like "    OEM Code Page (US (CP437))  ---> " are no longer selectable.

**Comment by thunderWhitecat** [comment]
Hi @lu1210,

Can you attach your sdkconfig file. It is very strange, so Lua RTOS has not interferences with esp-idf kconfig as far I can see.

**Comment by lu1210** [comment]
[sdkconfig.txt](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/1847110/sdkconfig.txt)

**Comment by lu1210** [comment]
[sdkconfig.txt](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/1847118/sdkconfig.txt)

**Comment by lu1210** [comment]
see attached sdkconfig file

**Comment by lu1210** [comment]
with the new update of esp-idf today, the error is corrected
