### ISSUE TITLE
Feature request: Expose esp32 touchpad functionality as sensor

### ISSUE THREAD

**Issue by bytebang** [whitecatboard/Lua-RTOS-ESP32#132]
Hi

I want to suggest to add the esp32 functionality of "capacitive touch inputs" to the operating system. 

Links:
- http://esp-idf.readthedocs.io/en/latest/api-reference/peripherals/touch_pad.html

**Comment by the0ne** [comment]
I needed touch functionality and I've recently (locally) added a module.
It's not finished yet but touch works and waking from sleep using touch works as well.
It's not yet available via github because currently it's only "all or nothing".

**Comment by chilipeppr** [comment]
Any latest on this? I'd like to use touch in an application as well for stepper motor control. Any code in any state would be appreciated! Thanks.

**Comment by the0ne** [comment]
@chilipeppr see PR https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/184 for a working implementation

**Comment by the0ne** [comment]
@chilipeppr the feature is available in [master](https://github.com/whitecatboard/Lua-RTOS-ESP32/tree/master)

**Comment by the0ne** [comment]
@bytebang and @chilipeppr please test using a current version
