### ISSUE TITLE
documentation: i2c module not listed in main page.

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#135]
In the list of modeules at https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki there is no link to https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/I2C-module

**Comment by thunderWhitecat** [comment]
Hi @xopxe,

Thanks for report this. I2C documentation has been added, and listed in the main page.

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/I2C-module
