### ISSUE TITLE
UPTIME is missing.

### ISSUE THREAD

**Issue by oskarirauta** [whitecatboard/Lua-RTOS-ESP32#139]
Lua-RTOS-ESP32 does not seem to have any "uptime" capability.
This should be made available (seconds/time from boot) - I made some testing with new board and was wondering if it was running smoothly for the whole night, and decided to check this at morning, but unfortunately there was no uptime command in shell (nor did I find anything similar for Lua)

**Comment by bytebang** [comment]
I think the following function should do the trick: https://www.freertos.org/a00021.html#xTaskGetTickCount

Unfortunately it is not  (yet) exposed via LUA

**Comment by oskarirauta** [comment]
Found it aswell- also something useful maybe in curl’s timeval.c, but I was not able to implement this...

Lähetetty iPhonesta

**Comment by gjongenelen** [comment]
I think you want to use **os.clock()**?

This return the amount of seconds counted since boot. Couldn't find any documentation about this command though.

**Comment by oskarirauta** [comment]
Perfect. Although, I still think it should be mapped to uptime command in shell.

Lähetetty iPhonesta

**Comment by thunderWhitecat** [comment]
Hi guys,

This feature will be added as soon as possible.

**Comment by oskarirauta** [comment]
Thanks. Not a big deal, but it is improvement definetly.

Lähetetty iPhonesta

**Comment by jolivepetrus** [comment]
Hi guys,

Added in commit https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Lua-RTOS-&-board-status.

**Comment by thunderWhitecat** [comment]
Hi guys,

Added in commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/050455de70a6b685642a75918db658b18ef10e3c.

Wiki: https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Lua-RTOS-&-board-status#osuptimetable

**Comment by oskarirauta** [comment]
Just tested this. Works perfectly. Thanks.
