### ISSUE TITLE
error running with latest esp-idf

### ISSUE THREAD

**Issue by loboris** [whitecatboard/Lua-RTOS-ESP32#14]
After latest esp-idf commits (09 Jan) Lua-RTOS-ESP32 builds OK, but cannot run:

`Guru Meditation Error of type LoadProhibited occurred on core  1. Exception was unhandled.
`

**Comment by thunderWhitecat** [comment]
Yes, we are working on it since this moorning.

Las commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/f3d7591151646a02a06194d7460340ba59afb90f solves this issue.

**Comment by thunderWhitecat** [comment]
Last commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/5003de4475c0f4240a33e1a8b342a8978d20ed42 solves issues related to mkdir and ls commands for spiffs and fat.

Pending tasks:

* show file size:  need changes for new struct dirent provided by esp-idf
* show mount points when ls /

**Comment by thunderWhitecat** [comment]
Work done in last commit (https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/480b6f35bab963654f19f80f527415c324b71788)
