### ISSUE TITLE
IPv6 seems to be broken

### ISSUE THREAD

**Issue by oskarirauta** [whitecatboard/Lua-RTOS-ESP32#148]
Only local link address (fe80:...) is available.

Could there be a option for disabling ipv6 support???

**Comment by thunderWhitecat** [comment]
@oskarirauta,

Can you explain in more detail what is your use case?

**Comment by oskarirauta** [comment]
I have IPv6 available, provided by my ISP and supported by my router (running openwrt/lede).

Device running Lua-RTOS-ESP32 reports following:
```
/ > netstat
wf: mac address 30:ae:a4:1e:74:28
   ip address 10.0.0.144 / netmask 255.255.0.0
   gw address 10.0.0.1
  ip6 address fe80:0000:0000:0000:32ae:a4ff:fe1e:7428

en: mac address 00:00:00:00:00:00
   ip address 0.0.0.0 netmask 0.0.0.0
   gw address 0.0.0.0
```

Therefore, only link local address seems to be listed when my network clients should receive 2 more addresses = ipv6 seems to be broken. Device in my case should receive 2 2001:xxxx:xxx:/64 addresses as well.

If by disabling ipv6 support - I only was thinking about disabling unsupported features as redundant. I am not familiar of how wide ipv6 support goes here, but all should be marked as experimental features due to... Well, being more or less experimental as my example points out :)

Or- I have some settings on my config.lua incorrectly, but I don't think so - I only set AP ssid and password there..

**Comment by the0ne** [comment]
@oskarirauta IPv6 is not yet properly supported by lwip.

you will probably need to change line 615 of esp-idf/components/lwip/include/lwip/port/lwipopts.h
`#define LWIP_IPV6                       1`
change to
`#define LWIP_IPV6                       0`

you may also want to comment out line 27 in components/sys/Makefile.projbuild
`CFLAGS += -DLWIP_IPV6=1`
change to 
`#CFLAGS += -DLWIP_IPV6=1`

**Comment by thunderWhitecat** [comment]
I close the issue, no feedback.
