### ISSUE TITLE
I2C don't support detach method

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#150]
/ > i2cBMP = i2c.attach(i2c.I2C0,i2c.MASTER)
/ > i2cBMP:detach()
stdin:1: '__index' chain too long; possible loop
stack traceback:
	stdin:1: in main chunk
	[C]: in ?
/ >

**Comment by thunderWhitecat** [comment]
Implemented in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/fe1fee4e539a3205dfabe2a5e5cfbbc7fab572c4.
