### ISSUE TITLE
Can't access SPI peripheral.

### ISSUE THREAD

**Issue by yawor** [whitecatboard/Lua-RTOS-ESP32#151]
Hi,

I have a ai-thinker.com esp32s devkit board (here's electrical schcematic http://pliki.propix.com.pl/images/nodemcu_esp-32s/nodemcu_32s_sch.png) with 4 MB of flash memory.

I've been able to successfully install Lua RTOS on it using either "Whitecat N1 ESP32 DEVKIT" or "Generic ESP32 board". The Lua RTOS boots, I'm able to connect to serial console and I've been able to configure wifi connection and ssh server.

But I'm trying to use SPI and I'm getting errors.

On "Whitecat N1 ESP32 DEVKIT", when trying to attach to SPI2:
```
/ > s = spi.attach(spi.SPI2, spi.MASTER, pio.GPIO5, 5000000, 8, 0)
assertion "ret==ESP_OK" failed: file "/root/esp/Lua-RTOS-ESP32/components/sys/drivers/spi.c", line 653, function: spi_ll_setup
abort() was called at PC 0x400d47a7 on core 0

Backtrace: 0x40095a77:0x3ffd86d0 0x40095bcf:0x3ffd86f0 0x400d47a7:0x3ffd8710 0x400e05d7:0x3ffd8740 0x400e13df:0x3ffd87b0 0x400ed8bc:0x3ffd87f0 0x400fe7e5:0x3ffd8830 0x40101df1:0x3ffd8860 0x400fea41:0x3ffd88b0 0x400fea61:0x3ffd88d0 0x40103a41:0x3ffd88f0 0x400fe415:0x3ffd8910 0x400febea:0x3ffd8990 0x401048ad:0x3ffd89c0 0x400fdd30:0x3ffd89f0 0x400fe00e:0x3ffd8a10 0x400fe24a:0x3ffd8a40 0x400fe7e5:0x3ffd8a70 0x400fea3a:0x3ffd8aa0 0x400fea61:0x3ffd8ac0 0x40103a41:0x3ffd8ae0 0x400fe415:0x3ffd8b00 0x400febea:0x3ffd8b80 0x401048ad:0x3ffd8bb0 0x400fdfc4:0x3ffd8be0 0x400d5797:0x3ffd8c10 0x400d542f:0x3ffd8c30
```

On "Whitecat N1 ESP32 DEVKIT" and "Generic ESP32 board", with SPI3:
```
/ > s = spi.attach(spi.SPI3, spi.MASTER, pio.GPIO5, 5000000, 8, 0)
spi3 at pins miso=GPIO19/mosi=GPIO23/clk=GPIO18
/ > s:select()
stdin:1: 83886087:invalid device
stack traceback:
	[C]: in method 'select'
	stdin:1: in main chunk
	[C]: in ?
/ > s:write(1)
stdin:1: 83886087:invalid device
stack traceback:
	[C]: in method 'write'
	stdin:1: in main chunk
	[C]: in ?
/ > s:deselect()
stdin:1: 83886087:invalid device
stack traceback:
	[C]: in method 'deselect'
	stdin:1: in main chunk
	[C]: in ?
```

On "Generic ESP32 board", I'm able to attach to SPI2, but I also get "invalid device" error when trying to use it (like with SPI3 above).

This happens on both the official releases and on self-built ones (using defconfig and then changing only flash programmer parameters).

--edit

I've also tried with "Whitecat N1 ESP32" and "Espressif Systems ESP32-CoreBoard" and they all behave like with "Generic ESP32 board", so no Abort/reboot, but I get "invalid device" error.

**Comment by xopxe** [comment]
We have the same problem with a Sparkfun ESP32  Thing, using a image built from sources.


    / > device = spi.attach(spi.SPI2, spi.MASTER, pio.GPIO15, 1000000, 8, 0) 
    spi2 at pins miso=GPIO12/mosi=GPIO13/clk=GPIO14
    / > device:select()
    stdin:1: 83886087:invalid device
    stack traceback:
        [C]: in method 'select'
        stdin:1: in main chunk
        [C]: in ?

**Comment by yawor** [comment]
I've started tracking the issue. The error is generated in `components/sys/drivers/spi.c` by checks in several functions like this:
```c
        if ((device < 0) || (device > SPI_BUS_DEVICES)) {
                return driver_error(SPI_DRIVER, SPI_ERR_INVALID_DEVICE, NULL);
        }
```
where `SPI_BUS_DEVICES` is defined as value `3`.

`device` is a number returned by function `spi_get_free_device`, called by `spi_ll_setup`:
```c
static int spi_get_free_device(int unit) {
        int i;

        for(i=0;i < SPI_BUS_DEVICES;i++) {
                if (!spi_bus[spi_idx(unit)].device[i].setup) return i;
        }

        return -1;
}
```
I think the value returned here must be greater or equal to `3` for some reason. It shouldn't be `-1` because it would error out sooner than call to `spi:select()` or other functions.

**Comment by yawor** [comment]
OK, it's not the above check of `device` value against `SPI_BUS_DEVICES`. The value is ok. It's the next check:
```c
        if (!spi_bus[spi_idx(unit)].device[device].setup) {
                return driver_error(SPI_DRIVER, SPI_ERR_DEVICE_NOT_SETUP, NULL);
        }
```
The error message is the same for `SPI_ERR_DEVICE_NOT_SETUP` and `SPI_ERR_INVALID_DEVICE`. It seems that the `setup` field in `spi_device_t` struct is not being set properly.

**Comment by yawor** [comment]
OK, the device's setup field is not set anywhere in the code. I'll post a PR in a moment which fixes this. I've tested SPI with a logic analyser and it works.
BTW when I do this:
```lua
s:select()
s:write(1, 2, 3, 4, 5)
s:deselect()
```
I see in the logic analyser that each single byte is sent quickly (according to the frequency set in the `spi.attach()` (it takes about 1.5 us at 5 MHz), but the delay between bytes is really big, even up to 37 us. It means that sending 5 bytes like above takes 5 bytes * 1.5 us + 4 delays * 36 us (average) = 151 us instead just about 8 to 10 us if there were no such delays. Also time from select to first byte and time from last byte to deselect are really big: 170 us and 81 us respectively.

**Comment by yawor** [comment]
Captured SPI signal when sending string "abcde" to show timing issue mentioned in my last comment:
![SPI capture](https://image.ibb.co/ektKuH/lua_rtos_spi_write.png)

**Comment by thunderWhitecat** [comment]
Please, try with last commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/3ccc656f52fead714be34414359b9c797d769498

that solves the following:

/ > s = spi.attach(spi.SPI2, spi.MASTER, pio.GPIO5, 5000000, 8, 0)
assertion "ret==ESP_OK" failed: file "/root/esp/Lua-RTOS-ESP32/components/sys/drivers/spi.c", line 653, function: spi_ll_setup
abort() was called at PC 0x400d47a7 on core 0

**Comment by thunderWhitecat** [comment]
Hi @yawor,

About the timing issues, please check this commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/936b6f0bf8e612b04d80d1ed4405e1a06d01ae65. Now the read/write data is stored into a buffer and spi bulk functions are used. This should speed up the transfers.

**Comment by yawor** [comment]
@jolivepetrus thanks. I can confirm that the transaction is now a little faster, without unnecessary pauses between bytes.

Unfortunately this doesn't help as the times from activating NSS line to first clock signal is still really big. I'm trying to interface with 868 MHz RFM12B module, which doesn't have any internal buffering on receiver side (it only stores a single received byte), so the timing is really strict. If the received byte is not read quickly enough, it gets overwritten (this situation can be detected by checking a status register, but this doesn't solve the issue in any way).

The module has an output nIRQ pin, which pulls down the line when something important is happening (like next byte received). The program needs to react to the interrupt by first requesting a status register and if there's a byte received, issuing a read command.

I've set up the interrupt by using (undocumented?) `pio.pin.interrupt` function to trigger only on falling edge. Unfortunately I'm getting a lot of missed bytes.

The incoming data has a baud rate of 9600 bps. This means I only have about 0.8 ms to react to an interrupt, check the status and read the byte before the next one rolls in.

I did some additional measurements:
1. time from the interrupt signal to activating NSS (status command): 0.83 ms
2. time from activating NSS to first SPI clock edge: 0.1 ms
3. time from last clock edge to deactivating NSS: 0.13 ms (about 1 ms passed from the interrupt and we've only read status register so far)
4. then there's a small delay (~ 50 us)
5. similar timings to 2 and 3 when issuing read command

I wonder why the delay between SPI transactions (50 us) is much smaller than the delays inside the transaction. Also the reaction time to interrupt alone can be responsible for missing one or two bytes at the beginning.

Is there anything that can be done to optimise interrupt reaction times and SPI operations or is the Lua interpreter just too slow for this? Do I need to try to write the low level stuff as a module in C instead? I'd like to have that Real Time from the Lua-RTOS name :). Both ESP32 and Lua are quite new to me, but I'm a quick learner, so maybe I could help. Just point me in the right direction.

Here's a code I'm writing, for reference:
```lua
-- RFM12B

local FREQUENCY = 1664 -- math.floor((868320000 - 860000000) / 5000) -- 868.320 MHz
local FSK_SHIFT = 48 -- (math.floor(60000 / 15000) - 1) << 4 -- 60000
local DATARATE = 35 -- math.floor((10000000 / 29 / 9600) - 0.5)

local CMD_CFG = 0x8000
local CFG_EL = 0x80
local CFG_EF = 0x40
--local CFG_BAND_315 = 0x00
--local CFG_BAND_433 = 0x10
local CFG_BAND_868 = 0x20
--local CFG_BAND_915 = 0x30
--local CFG_XTAL_8_5PF  = 0x00
--local CFG_XTAL_9_0PF  = 0x01
--local CFG_XTAL_9_5PF  = 0x02
--local CFG_XTAL_10_0PF = 0x03
--local CFG_XTAL_10_5PF = 0x04
--local CFG_XTAL_11_0PF = 0x05
--local CFG_XTAL_11_5PF = 0x06
--local CFG_XTAL_12_0PF = 0x07
local CFG_XTAL_12_5PF = 0x08
--local CFG_XTAL_13_0PF = 0x09
--local CFG_XTAL_13_5PF = 0x0A
--local CFG_XTAL_14_0PF = 0x0B
--local CFG_XTAL_14_5PF = 0x0C
--local CFG_XTAL_15_0PF = 0x0D
--local CFG_XTAL_15_5PF = 0x0E
--local CFG_XTAL_16_0PF = 0x0F

local CMD_PWRMGT = 0x8200
local PWRMGT_ER = 0x80
--local PWRMGT_EBB = 0x40
local PWRMGT_ET = 0x20
--local PWRMGT_ES = 0x10
--local PWRMGT_EX = 0x08
--local PWRMGT_EB = 0x04
--local PWRMGT_EW = 0x02
local PWRMGT_DC = 0x01

local CMD_FREQUENCY = 0xA000

local CMD_DATARATE = 0xC600
--local DATARATE_CS = 0x80

local CMD_RXCTRL = 0x9000
local RXCTRL_P16_VDI = 0x400
local RXCTRL_VDI_FAST = 0x000
--local RXCTRL_VDI_MEDIUM = 0x100
--local RXCTRL_VDI_SLOW = 0x200
--local RXCTRL_VDI_ALWAYS_ON = 0x300
--local RXCTRL_BW_400 = 0x20
--local RXCTRL_BW_340 = 0x40
--local RXCTRL_BW_270 = 0x60
local RXCTRL_BW_200 = 0x80
--local RXCTRL_BW_134 = 0xA0
--local RXCTRL_BW_67 = 0xC0
local RXCTRL_LNA_0 = 0x00
--local RXCTRL_LNA_6 = 0x08
--local RXCTRL_LNA_14 = 0x10
--local RXCTRL_LNA_20 = 0x18
local RXCTRL_RSSI_103 = 0x00
--local RXCTRL_RSSI_97 = 0x01
--local RXCTRL_RSSI_91 = 0x02
--local RXCTRL_RSSI_85 = 0x03
--local RXCTRL_RSSI_79 = 0x04
--local RXCTRL_RSSI_73 = 0x05
--local RXCTRL_RSSI_67 = 0x06
--local RXCTRL_RSSI_61 = 0x07

local CMD_DATAFILTER = 0xC228
local DATAFILTER_AL = 0x80
--local DATAFILTER_ML = 0x40
--local DATAFILTER_S = 0x10

local CMD_FIFORESET = 0xCA00
--local FIFORESET_SP = 0x08
--local FIFORESET_AL = 0x04
local FIFORESET_FF = 0x02
local FIFORESET_DR = 0x01

--local CMD_SYNCPATTERN = 0xCE00

local CMD_READ = 0xB000

local CMD_AFC = 0xC400
--local AFC_AUTO_OFF = 0x00
--local AFC_AUTO_ONCE = 0x40
local AFC_AUTO_VDI = 0x80
--local AFC_AUTO_KEEP = 0xC0
local AFC_LIMIT_OFF = 0x00
--local AFC_LIMIT_16 = 0x10
--local AFC_LIMIT_8 = 0x20
--local AFC_LIMIT_4 = 0x30
--local AFC_ST = 0x08
--local AFC_FI = 0x04
local AFC_OE = 0x02
local AFC_EN = 0x01

local CMD_TXCONF = 0x9800
--local TXCONF_MP = 0x100
local TXCONF_POWER_0 = 0x00
--local TXCONF_POWER_3 = 0x01
--local TXCONF_POWER_6 = 0x02
--local TXCONF_POWER_9 = 0x03
--local TXCONF_POWER_12 = 0x04
--local TXCONF_POWER_15 = 0x05
--local TXCONF_POWER_18 = 0x06
--local TXCONF_POWER_21 = 0x07

local CMD_PLL = 0xCC02
--local PLL_DDY = 0x08
--local PLL_DDIT = 0x04
local PLL_BW0 = 0x01

local CMD_TX = 0xB800

--local CMD_WAKEUP = 0xE000

--local CMD_DUTYCYCLE = 0xC800
--local DUTYCYCLE_ENABLE = 0x01

local CMD_STATUS = 0x0000
--local STATUS_RGIT = 0x8000
local STATUS_FFIT = 0x8000
--local STATUS_POR = 0x4000
--local STATUS_RGUR = 0x2000
--local STATUS_FFOV = 0x2000
--local STATUS_WKUP = 0x1000
--local STATUS_EXT = 0x0800
--local STATUS_LBD = 0x0400
--local STATUS_FFEM = 0x0200
--local STATUS_ATS = 0x0100
--local STATUS_RSSI = 0x0100
--local STATUS_DQD = 0x0080
--local STATUS_CRL = 0x0040
--local STATUS_ATGL = 0x0020

local CMD_RESET = 0xffff

local CMD_PWRMGT_DEFAULT = CMD_PWRMGT | PWRMGT_DC
--local CMD_PWRMGT_TRANSMIT = CMD_PWRMGT_DEFAULT | PWRMGT_ET
local CMD_PWRMGT_RECEIVE = CMD_PWRMGT_DEFAULT | PWRMGT_ER
local CMD_CLEAR_FIFO = CMD_FIFORESET | FIFORESET_DR | (8 << 4)
local CMD_ACCEPT_DATA = CMD_CLEAR_FIFO | FIFORESET_FF

local INIT_COMMANDS = {
    CMD_CFG | CFG_EL | CFG_EF | CFG_BAND_868 | CFG_XTAL_12_5PF,
    CMD_PWRMGT_DEFAULT,
    CMD_FREQUENCY | FREQUENCY,
    CMD_DATARATE | DATARATE,
    CMD_RXCTRL | RXCTRL_P16_VDI | RXCTRL_VDI_FAST | RXCTRL_BW_200 | RXCTRL_LNA_0 | RXCTRL_RSSI_103,
    CMD_DATAFILTER | DATAFILTER_AL | 4,
    CMD_CLEAR_FIFO,
    CMD_AFC | AFC_AUTO_VDI | AFC_LIMIT_OFF | AFC_OE | AFC_EN,
    CMD_TXCONF | TXCONF_POWER_0 | FSK_SHIFT,
    CMD_PLL | PLL_BW0,
    CMD_PWRMGT_RECEIVE,
}

local dev
local buffer = {}
local packets = {}
local recvd = 0
local disableCB = false
local recheck = false
local status
local packet_rcvd = event.create()

function rfm12_readwrite(data)
    dev:select()
    local ret = dev:readwrite((data & 0xff00) >> 8, data & 0xff)
    dev:deselect()
    return ret[0] << 8 | ret[1]
end

function rfm12_init()
    dev = spi.attach(spi.SPI3, spi.MASTER, pio.GPIO5, 2000000, 8, 0)
    thread.start(extafree_packet)

    pio.pin.setdir(pio.OUTPUT, pio.GPIO12)
    pio.pin.setlow(pio.GPIO12)
    thread.sleepms(1)
    pio.pin.sethigh(pio.GPIO12)
    for i, cmd in ipairs(INIT_COMMANDS) do
        rfm12_readwrite(cmd)
    end
    rfm12_readwrite(CMD_STATUS)
    pio.pin.interrupt(pio.GPIO21, rfm12_callback, pio.pin.IntrNegEdge)
    rfm12_readwrite(CMD_CLEAR_FIFO)
    rfm12_readwrite(CMD_ACCEPT_DATA)
end

function extafree_packet()
    while true do
        packet_rcvd:wait()
        while #packets > 0 do
            print(table.concat(table.remove(packets, 1), ' '))
        end
        packet_rcvd:done()
    end
end

function rfm12_callback()
    if disableCB then return end
    disableCB = true
    while true do
        status = rfm12_readwrite(CMD_STATUS)
        recheck = false
        if status & STATUS_FFIT ~= 0 then
            recheck = true
            recvd = recvd + 1
            buffer[recvd] = rfm12_readwrite(CMD_READ) & 0xff
            if recvd == 11 then
                rfm12_readwrite(CMD_CLEAR_FIFO)
                rfm12_readwrite(CMD_ACCEPT_DATA)
                table.insert(packets, buffer)
                buffer = {}
                recvd = 0
                packet_rcvd:broadcast()
            end
        end
        if not recheck then break end
    end
    disableCB = false
end
```

**Comment by thunderWhitecat** [comment]
@yawor,

It should feasible to do that from Lua. Please, try with commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/8e2a39b1a5cba6450c341e21f7afd15ba7fd8e6b, that solves some timing issues.

**Comment by yawor** [comment]
@jolivepetrus it much much better now. The reaction to the interrupt now went from around 830 us down to just about 73 us. That's 10 times improvement :).
I still see some receive errors (malformed packets), but I need to investigate if it's an algorithm problem or the times are still too loose - the time the NSS is being active is the only thing left untouched.

BTW what happens when another interrupt is generated when the callback started by the previous one is still executing? Is it queued and calls the callback when previous finishes? Or starts another thread with another callback? Or maybe it's automatically ignored?

When I started sending packets more frequently (about 10-12 in a second, each packet is 11 bytes long) I started getting:
```
Guru Meditation Error: Core  0 panic'ed (LoadProhibited)
. Exception was unhandled.
Core 0 register dump:
PC      : 0x400f3eb5  PS      : 0x00060d30  A0      : 0x800f4398  A1      : 0x3ffed140  
A2      : 0x3ffd9600  A3      : 0x3ffd969c  A4      : 0x3ffe4e28  A5      : 0x3ffd9600  
A6      : 0x3ffdbd64  A7      : 0x00000004  A8      : 0x00000002  A9      : 0x3ffe4e44  
A10     : 0x3ffd9c08  A11     : 0x000000ff  A12     : 0x00000000  A13     : 0x00000001  
A14     : 0x0000cdcd  A15     : 0x00000040  SAR     : 0x0000001b  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x400012e5  LEND    : 0x40001309  LCOUNT  : 0x800fdacb  

Backtrace: 0x400f3eb5:0x3ffed140 0x400f4395:0x3ffed170 0x400ff68a:0x3ffed190 0x40100275:0x3ffed1c0 0x400f4d15:0x3ffed210 0x400f4d35:0x3ffed230 0x4010268c:0x3ffed250 0x400eb405:0x3ffed270
```

**Comment by thunderWhitecat** [comment]
@yawor,

Do you use the gdisplay code in your code?

**Comment by yawor** [comment]
@jolivepetrus no. There's nothing more than the code I've pasted in my previous comment. I only have the RFM12B connected (SPI full duplex + one GPIO for IRQ and one GPIO in output mode for RFM12B reset).
I don't even have any network services running right now (wifi is not enabled). In autorun.lua I only load the rfm12b.lua and call the rfm12_init function.

**Comment by thunderWhitecat** [comment]
@yawor,

Ok, please try with https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/f9328aa43af1578088c63dca797a49567f9c0690.

The Lua interrupt management is based in the deferred interrupt concept, where the callback is executed outside the ISR (to resolve, for example, stack size issues), but a real ISR is simulated. This means that once the interrupt is received and queued, the GPIO ISR is detached and attached again when the Lua callback finish; so there is a possibility to loss interrupts. This was is due to an arbitrary design decision, that we can remove.

**Comment by yawor** [comment]
@jolivepetrus on the f9328aa43af1578088c63dca797a49567f9c0690 I now only see a sporadic receive errors (I can work with that, the protocol I'm working repeats each packet 2-3 times anyway). Also I've spammed the receiver with a ton of packets in a short time and I didn't see guru meditation anymore.
I don't see any noticeable difference with d70cdfe544239955a702c6aaaf9c2a375c2caa55, but looking at the commit, it seems to be important too.

Regarding the ISR being disabled during callback, I think it's reasonable. The original code I'm porting the RFM12B support from (running on Atmega 328) is disabling the interrupt in the interrupt mask register when entering the ISR anyway so this should also work. I need to test if `pio.pin.IntrLowLevel` could be better than `pio.pin.IntrNegEdge` in my case. The RFM12B module keeps the nIRQ low until it gets a proper command, depending on the interrupt reason.

-- edit --

I've tested with `pio.pin.IntrLowLevel` but as soon as a packet is received, the Lua-RTOS freezes and ESP32 needs to be rebooted by pressing the reset button.

**Comment by thunderWhitecat** [comment]
Hi @yawor,

Issue with pio.pin.IntrLowLevel is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/439261cccebb3b8daa4d631a53d0352546660139.

**Comment by yawor** [comment]
@jolivepetrus 

I see what you did in that commit. It doesn't starve the CPU anymore, but I don't think this is an expected behaviour. Right now you're emulating IntrNegEdge and IntrPosEdge behaviour for IntrLowLevel and IntrHighLevel respectively so there's practically no real difference between them (besides being less optimal).
I think the expected behaviour for IntrLowLevel and IntrHighLevel is to re-queue the callback as long, as the state of the pin has selected value. So when the callback finishes, the C code calling the Lua callback function should check the pin state and re-queue itself if needed. The tricky part is probably to do this in a way so it won't starve the CPU again.

**Comment by thunderWhitecat** [comment]
@yawor,

I'm a bit confusing about the behaviour of a GPIO interrupt of type GPIO_INTR_HIGH_LEVEL / GPIO_INTR_LOW_LEVEL. In my tests, using only esp-idf, the interrupt is fired indefinitely until the gpio logic level changes.

**Comment by yawor** [comment]
@jolivepetrus 

Yeah, it should work like that, because that type of interrupt is not triggered by the edge (pin state change), but by a pin state itself. So for IntrLowLevel, the callback should be re-queued after it finishes as long, as the pin is pulled low. Now how to do it without starving the CPU - I don't know.
With your last commit, after triggering the callback, the pin still needs to go high and then low again to fire it again, so it behaves like IntrNegEdge.

**Comment by thunderWhitecat** [comment]
@yawor,

I have reverted the commit, and I see that in my case the CPU was starved due to that I attach the interrupt into a very high priority:

```
-- This starves
pio.pin.interrupt(pio.GPIO14, function(value)
...
...
end, pio.pin.IntrLowLevel, nil, nil, 25)
```

```
-- This don't starves
pio.pin.interrupt(pio.GPIO14, function(value)
...
...
end, pio.pin.IntrLowLevel, nil, nil, 20)
```

FYI the Lua interpreter has a priority of 20.

**Comment by yawor** [comment]
Yeah, I think I've made a mistake in my code, which caused the RFM12B never clearing the interrupt line, keeping the pin low and that somehow caused starvation. I haven't changed the priority.
I've also tried checking out the commit before that change and now it doesn't starve. I'm sorry for the unnecessary change you've had to do. I think you can safely revert this commit.

But unfortunately the SPI is still too slow for some reason and I loose some packets. I wanted to check if the `spi:select()` and `spi:deselect()` are the source of the delays, so I permanently set `spi:select()` just after creating the spi device and then manually pulled the pin high. I've temporarily replaced `spi:select()` and `spi:deselect()` with `pio.pin.setlow()` and `pio.pin.sethigh()` to get around the whole logic behind the select and deselect. But the time from NSS being pulled down to first SPI CLK signal didn't change in any significant way. So it means it's not a matter of select and deselect.

This means that it's the `spi:readwrite` (switching to `spi:write` for testing doesn't change the timings) that still adds delays before sending first byte and after sending the last byte.

![timings2](https://cdn.pbrd.co/images/HjwCzRK.png)

Here's another timing diagram. Each transfer is 16 bits and, as you can see, there's no delay after each 8 bits, thanks to your awesome work on this. But there's still a big delay between NSS (channel 2 on the diagram) going down and first clock edge (channel 3). Then there's again a big delay until the NSS goes up again. In this example, that first transaction has first delay of 144 us and the second delay of 88 us. For some reason next transaction (and other following that one) seems to have shorter first delay (~68 us).

Do you think there's a chance of lowering those times somehow? I've been looking at the source code and I don't see where those delays could come from. There's really nothing before writing data to the TX register that could cause them.

**Comment by yawor** [comment]
@jolivepetrus 
I've decided to make a test using just a small C program based on ESP-IDF to check if the issue is with the ESP32 itself or is it something on the firmware side. Here's my code:
```c
#include <string.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "driver/spi_master.h"
#include "soc/gpio_struct.h"
#include "driver/gpio.h"

esp_err_t ret;
spi_device_handle_t spi;

void send(uint16_t data) {
    uint8_t _data[2];
    _data[0] = (data & 0xff00) >> 8;
    _data[1] = (data & 0xff);

    spi_transaction_t t;
    memset(&t, 0, sizeof(t));
    t.length = 2 * 8;
    t.tx_buffer = _data;
    ret = spi_device_transmit(spi, &t);
    ESP_ERROR_CHECK(ret);
}

void app_main() {
    spi_bus_config_t buscfg = {
        .miso_io_num=19,
        .mosi_io_num=23,
        .sclk_io_num=18,
        .max_transfer_sz=2,
    };
    spi_device_interface_config_t devcfg = {
        .clock_speed_hz=2*1000*1000,
        .mode=0,
        .spics_io_num=5,
        .queue_size=7,
    };
    ret = spi_bus_initialize(VSPI_HOST, &buscfg, 1);
    ESP_ERROR_CHECK(ret);
    ret = spi_bus_add_device(VSPI_HOST, &devcfg, &spi);
    ESP_ERROR_CHECK(ret);

    send(0x1234);
    send(0x5678);
}
```
and here's the logic analyser output:
![spi timings in C](https://cdn.pbrd.co/images/HjOkuSl.png)

As you can see, the NSS signal (the first line) goes down just 0.25 us before first CLK edge and goes up in the same time after last CLK edge. So at least I know that SPI hw in ESP32 is capable of much better timings.

So the question is how to achieve similar timings in Lua-RTOS. Or at least closer to these ones than to what's currently achievable in Lua.

**Comment by thunderWhitecat** [comment]
@yawor, @xopxe,

Please, discuss the performance issues in https://github.com/whitecatboard/Lua-RTOS-ESP32/issues/162.

**Comment by thunderWhitecat** [comment]
@yawor,

About NSS timing, please try with commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/05bd970013556eb8a0b06efe8594495a772a2bdf, it should work now.

**Comment by the0ne** [comment]
@yawor please comment or close this issue - thanks!

**Comment by yawor** [comment]
I'm sorry for the lack of input from me. I've moved on with working directly with esp-idf and platformio/esphome. I think there'll always be too much overhead with LuaRTOS regarding SPI for my specific use case. I still think that LuaRTOS is great piece of software but it's just not what I need for this project.
