### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by oskarirauta** [whitecatboard/Lua-RTOS-ESP32#156]
Build fails due to missing references to wifi related code.
Updating esp-idf fixed the issue.

I created a pull request [PR #155](https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/155) which contains all ( it's single change in Makefile regarding to esp-idf commit used for while building ) necessary changes to sort this issue out.

**Comment by yawor** [comment]
I've had no problems building current master branch using provided board configurations.

**Comment by oskarirauta** [comment]
Try starting from fresh.
Issue occurred  with Mac OS X 10.13.4

Either way - if this issue affects some systems, but provides a fix on all systems... I guess it won't hurt.

**Comment by yawor** [comment]
I've checked out your branch and I can confirm it builds correctly.

**Comment by oskarirauta** [comment]
Yes. I also tested it and was able to build image without issues using this newer commit of esp-idf.

**Comment by mafrmt00** [comment]
With Linux, after building Lua (successfully) IDF is not working with the provided examples anymore. Even "Hello World" fails. Only after clean IDF checkout, examples work again.
With MacOS I was not able to build Lua due to some issue with  libpp.a (wifi delete queue).
But same effect on IDF.

**Comment by thunderWhitecat** [comment]
Hi guys,

Lua RTOS patch some esp-idf features. To work only with idf do a make restore-idf from the Lua RTOS main folder. This restore esp-idf to it's initial state.

**Comment by mafrmt00** [comment]
Now also Linux build fails:
/home/mafrmt00/esp/esp-idf/components/esp32/lib/libpp.a(pp.o):(.text.pp_deattach_phase2+0xc): undefined reference to `wifi_delete_queue'
/home/mafrmt00/esp/esp-idf/components/esp32/lib/libpp.a(pp.o): In function `pp_deattach_phase2':
(.text.pp_deattach_phase2+0x23): undefined reference to `wifi_delete_queue'
/home/mafrmt00/esp/esp-idf/components/esp32/lib/libpp.a(pp.o):(.text.pp_attach+0x20): undefined reference to `wifi_create_queue'

**Comment by thunderWhitecat** [comment]
@mafrmt00,

From Lua RTOS main folder:

make upgrade-idf
make flash

**Comment by thunderWhitecat** [comment]
Hi guys,

I don't have feedback about this issue. Please, reopen in case you need more assistance.
