### ISSUE TITLE
GPS Position is off by about 1km

### ISSUE THREAD

**Issue by mafrmt00** [whitecatboard/Lua-RTOS-ESP32#158]
When using the GPS Sensor, the position is off about 1.2km to the south. 
The position rarely changes, even the last digit ist very stable.
When the receiver is moved indoors, the position goes to 0, also the satellite count.

When the NMEA Data of the GPS is dumped with the Terminal example and analyzed, the position is correct.

**Comment by mafrmt00** [comment]
In Lua-RTOS-ESP32/components/nmea/nmea0183.c

Line 122:            
seconds = (double)atoi(current) / (double)1000000;

Should be:
seconds = (double)atoi(current) / (double)10000;

**Comment by gmenier** [comment]
Same problem here. There is indeed an offset (NEO-6M).

**Comment by the0ne** [comment]
@mafrmt00 can you create a [PR](https://github.com/whitecatboard/Lua-RTOS-ESP32/pulls) for this?

**Comment by adrianvielsack** [comment]
#277 should fix this, regardless of precision

**Comment by the0ne** [comment]
@adrianvielsack Thanks a lot!
@jolivepetrus what do you think about #277?

**Comment by the0ne** [comment]
@adrianvielsack thanks for your fix - it has been accepted into Lua-RTOS!
@jolivepetrus thanks for merging!
