### ISSUE TITLE
MQTT subscribe callback doesnt filter topics (?)

### ISSUE THREAD

**Issue by gmenier** [whitecatboard/Lua-RTOS-ESP32#161]
When subscribing to different topics, it seems that any of the received topics triggers all the callbacks (for all topics). Tested on the last build for esp32 things (mqttspy + different brokers)

Regards
Gildas

**Comment by thunderWhitecat** [comment]
@gmenier,

Thanks for report this. It is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/178cb7e2d3d39a18133fe73fefc193eef42274bc.

**Comment by gmenier** [comment]
Thank you ! It works now - you can close the issue I guess.
