### ISSUE TITLE
Sensor timeout when wifi on (sta)

### ISSUE THREAD

**Issue by gmenier** [whitecatboard/Lua-RTOS-ESP32#163]
s = sensor.attach("DHT11", pio.GPIO15)

while true do
  print("temp: "..s:read("temperature").." humidite : "..s:read("humidity"))
  tmr.delayms(500)
end

fails (after a few iterations) to a timeout in the method read when wifi (sta) is on (started thru the config.lua). 
 
Works perfectly when wifi is off (net.wf.stop()).

Tested using 5 different DHT11. EspThing latest build.

Regards
G.

**Comment by thunderWhitecat** [comment]
@gmenier,

I can't reproduce with all upgraded.

Please, from Lua RTOS root folder, try:

git pull
make upgrade-idf
make flash

... but DHT sensor series must be implemented using the RMT module for best performance (see https://github.com/whitecatboard/Lua-RTOS-ESP32/issues/165).

**Comment by thunderWhitecat** [comment]
@gmenier,

This is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/9955a645464a81e44f14e4e5c62e2983039bfc40.

**Comment by gmenier** [comment]
Nice ! Thank you (amazing support :-) ). Closing.
