### ISSUE TITLE
http server memory leak

### ISSUE THREAD

**Issue by mgrusik** [whitecatboard/Lua-RTOS-ESP32#164]
Hi, at each connection, about ~300 bytes of heap memory are leak, how can this problem be solved?

**Comment by the0ne** [comment]
How did you measure that?

Maybe only seeing the following, taken from http://lwip.wikia.com/wiki/Netconn_bind ?
_Only after some time (minutes) the resources are completely cleared in the underlying stack due to the need to follow the TCP specification and go through the TCP timewait state._

**Comment by thunderWhitecat** [comment]
Hi guys!

Closing the issue, as we don't have any feed-back, and required information were not provided.
