### ISSUE TITLE
Small enhancement of the functional scope of the integration of lua sockets method settimout (sec)

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#167]
Currently, only blocking (settimeout ()) or an approximate 1 second timeout (settimeout (sec ~= 0) is supported. A variable timeout rating should be possible.

**Comment by thunderWhitecat** [comment]
@lu1210,

I don't understand.

**Comment by lu1210** [comment]
According to the LUA socket description method  "settimeout" is specified as follow

"master:settimeout(value [, mode])
client:settimeout(value [, mode])
server:settimeout(value [, mode])

Changes the timeout values for the object.
By default, all I/O operations are blocking.
That is, any call to the methods send, receive, and accept will block indefinitely,
until the operation completes.
The settimeout method defines a limit on the amount of time the I/O methods can block.
When a timeout is set and the specified amount of time has elapsed, the affected methods give up and fail with an error code.

The amount of time to wait is specified as the value parameter, in seconds."
----------------

Cuurent implementation: Only blocking (settimeout ()) or
an approximate 1 second timeout (settimeout (sec ~= 0)) independent form sec value t is implemented.
----------------
Requested implementation: A variable timeout according to the description of the parameter value should be possible
