### ISSUE TITLE
net.wf.scan() : wifi not stop (?)

### ISSUE THREAD

**Issue by gmenier** [whitecatboard/Lua-RTOS-ESP32#170]
Commit 3c1591  build ( the wcc version seems stuck)

/ > net.wf.scan()
E (46457) wifi: esp_wifi_deinit 768 wifi not stop
stdin:1: 134217746:driver was not stopped
stack traceback:
	[C]: in field 'scan'
	stdin:1: in main chunk
	[C]: in ?

**Comment by thunderWhitecat** [comment]
@gmenier,

Thanks for report this. Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/5404725e4d26f0e4d40533018d603e0d513afa60.
