### ISSUE TITLE
Running make SDKCONFIG_DEFAULTS=xxx defconfig doesn't produce the .board file

### ISSUE THREAD

**Issue by yawor** [whitecatboard/Lua-RTOS-ESP32#172]
Hi,

I don't know if this is intentional or not, but when preparing the compilation by first running
`make SDKCONFIG_DEFAULTS=xxx defconfig` (where xxx is a proper board name of course), the .board file is not being generated. I've looked at the Makefile and the .board file is only generated when a user starts a build without having any sdkconfig file present.

The lack of the .board file causes the `boards/boards.py` script to raise an error when parsing the arguments, as the `$(BOARD)` variable is empty and the second argumente is taken as a first one (which should be a board number).

**Comment by thunderWhitecat** [comment]
@yawor,

Thanks for report this. Should be fixed in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/62d8384eea47b7bc060bd0fdf27e62248b347afb.
