### ISSUE TITLE
SD card 

### ISSUE THREAD

**Issue by yurybotov** [whitecatboard/Lua-RTOS-ESP32#173]
Wrover module. Connected to sd like this: https://dl.espressif.com/dl/schematics/ESP-WROVER-KIT_SCH-2.pdf ,  can't mount sd card file system:
rst:0x1 (POWERON_RESET),boot:0x3f (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0018,len:4
load:0x3fff001c,len:3512
load:0x40078000,len:0
ho 12 tail 0 room 4
load:0x40078000,len:12680
entry 0x400784f0
Booting Lua RTOS...
[2J[1;1H  /\       /\
 /  \_____/  \
/_____________\
W H I T E C A T
Lua RTOS beta 0.1. Copyright (C) 2015 - 2018 whitecatboard.org
build 1527751367
commit 54f882faa0b375652f5e61734b3e4a0017fa0c82
Running from factory partition
board type ESP-WROVER-KIT
cpu ESP32 rev 1 at 240 Mhz
spiffs0 start address at 0x310000, size 512 Kb, partition spiffs
spiffs0 mounted
sd0 is at mmc0
fat0 can't mounted (error 261)
can't redirect console messages to file system, an SDCARD is needed
Lua RTOS beta 0.1 powered by Lua 5.3.4
Executing /system.lua ...
Starting ethernet ...
lua: /system.lua:97: attempt to index a nil value (field 'en')
stack traceback:
	/system.lua:97: in main chunk
	[C]: in ?
Executing /autorun.lua ...
/ >
SD card (SanDisc 2Gb/Fat), card-reader and wire - tested.

**Comment by thunderWhitecat** [comment]
@yurybotov,

Thanks for report this. Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/62ce4e5ae537a878c92c588e00d15462332550e0.
