### ISSUE TITLE
do not use c++ reserved word to allow building

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#175]
In components/lua/modules/sys/error.h there is a variable called "new", which is a reserved word in c++ and breaks building of cpp files when they include anything that uses errors.
Just renaming to anything else, like "new_thing" fixes it.

**Comment by thunderWhitecat** [comment]
@xopxe,

Thanks for report this, solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/0f7813effa99086c98f6207428656c7d3534ae55.
