### ISSUE TITLE
i2c default pins do not match pinout

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#181]
In https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/master/components/sys/Kconfig the default pins for SCL and SDA in channel 0 (menu entry "I2C pin map" ) are 21 and 22, respectively. The pinout charts I have seen (like https://cdn.sparkfun.com/assets/learn_tutorials/5/0/7/esp32-thing-graphical-datasheet-v02.png) have them backwards: SDA on pin 21 and SCL on 22.

**Comment by thunderWhitecat** [comment]
@xopxe,

Sorry, this is a too old issue ...

I have just push to the wiki all the information related to the hardware mappings (and others) for each supported board. Remember, that in Lua RTOS each board has it's own sdkconfig with the right values (Kconfig is only a template).

Mappings for ESP32 thing:

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Firmware-SparkFun-ESP32-Thing#hardware-mapping

If you are interested in other boards:

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Official-precompiled-Lua-RTOS-firmwares

Please, reopen if you need more assistance.
