### ISSUE TITLE
Make the I2C_BUS_DEVICES number configurable trough menuconfig

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#182]
The max number of i2c devices is hardwired in components/sys/drivers/i2c.h as 

#define I2C_BUS_DEVICES 3

This makes for weird errors when you add more than 3 i2c devices. Perhaps this value should be exposed as an entry in menuconfig so it can be easily changed (and discovered).

**Comment by thunderWhitecat** [comment]
@xopxe,

Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/e258a893a2b318a256d364ebb0edfdfa1729dc0c.
