### ISSUE TITLE
pack.unpack not working correct

### ISSUE THREAD

**Issue by thilo-hub** [whitecatboard/Lua-RTOS-ESP32#187]
Hi there

there are two issues I see with the pack packet:
The unpack has issues with small ascii characters ( unpack does not work - see example below)
// > s=string.char(5)
/ > print(pack.pack(s))
01400500
/ > print(pack.pack(pack.unpack("01400500")))
014000     
============ BAD RESULT ==========

The pack has issues with small ascii
/ > r=string.char(65,0,66)
/ > print( #r)
3
/ > print(pack.pack(r))
01404100
===== BAD RESULT =======

**Comment by the0ne** [comment]
@thilo-hub I can reproduce both
first one looks like some kind of trim() issue
second one looks like truncation issue

**Comment by thunderWhitecat** [comment]
@thilo-hub, @the0ne,

Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/f117ed11fe950287548b26246336df6cf0f78b53.
