### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by thilo-hub** [whitecatboard/Lua-RTOS-ESP32#188]
The text under:
https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/GDISPLAY-module#gdisplaysetorientorientation

Is a cut & paster error for the color stuff

**Comment by the0ne** [comment]
@thilo-hub do you mean this part?

> The default color depends on the display chipset, for example in TFT displays it is black, and in monochrome LCD displays it is white. In general, the default color is one that keeps all of the screen pixels off.

This is not a copy-paste error but further explains the _default color_ from the sentence before:

> Set the display orientation, and clear the screen to the default color.
