### ISSUE TITLE
sending can messages ignores fifo status

### ISSUE THREAD

**Issue by thilo-hub** [whitecatboard/Lua-RTOS-ESP32#189]
sendin can frames too fast can cause data loss

**Comment by the0ne** [comment]
@thilo-hub work has been started to migrate to the esp-idf can driver - you can test it using commit 
670d405 from PR https://github.com/whitecatboard/Lua-RTOS-ESP32/pull/267

**Comment by the0ne** [comment]
@thilo-hub were you able to try the new implementation?

**Comment by the0ne** [comment]
PR confirmed to be ok, closing this.
