### ISSUE TITLE
BME680 support?

### ISSUE THREAD

**Issue by skitsanos** [whitecatboard/Lua-RTOS-ESP32#191]
Not an issue, but rather a question.

Is there any BME-680 support implemented in lua-rtos? and if yes, how do i access it?

Thanks.

**Comment by thunderWhitecat** [comment]
@skitsanos,

At this time, no, but it would be great!.

**Comment by the0ne** [comment]
Looks like there is an implementation available: https://github.com/BoschSensortec/BME680_driver

**Comment by elsbiet** [comment]
i'm slightly confuse because

    bme = sensor.attach("BME280", i2c.I2C0, 0x77, 400)
    ..
    temperature = bme:read("temperature")
    humidity = bme:read("humidity")
    pressure = bme:read("pressure")

used to work fine.

--> https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/Sensor-module

**Comment by the0ne** [comment]
@skitsanos are you able to integrate the [mentioned implementation](https://github.com/BoschSensortec/BME680_driver) into Lua-RTOS? Can you create a PR?

**Comment by the0ne** [comment]
If you have the HW available, feel free to create a PR.
