### ISSUE TITLE
Compiling a custom windows binary for the Whitecat console

### ISSUE THREAD

**Issue by MiLeG** [whitecatboard/Lua-RTOS-ESP32#195]
Hello everyone.
I am trying to compile a custom .exe of the whitecat console after I added my board and changed some of the default pins in the boards section. I have downloaded and installed all of the dependencies and Linux tools used and changed the env file to my library paths but I'm still getting the following error:

>make clean
process_begin: CreateProcess(NULL, uname, ...) failed.
makefile:247: \make\project.mk: No such file or directory
'test' is not recognized as an internal or external command,
operable program or batch file.
'test' is not recognized as an internal or external command,
operable program or batch file.
make: *** No rule to make target `\make\project.mk'.  Stop.

Thanks!

**Comment by thunderWhitecat** [comment]
@MiLeG,

Whitecat console is written in Go lang, but seems that you are trying to build Lua RTOS, not the Whitecat console.

**Comment by MiLeG** [comment]
Yeah, basically I need a custom Lua RTOS build for my board. How can I do this without adding a new board in the "boards" folder and compiling the entire thing?

**Comment by thunderWhitecat** [comment]
This should works:

1) Start, for example using the "Espressif Systems ESP32-CoreBoard"

2) Change the configuration with make menuconfig, and test it

3) When configuration for your board is ok, you make a copy of the sdkconfig file, for example yourboardconfig.

4) Finally you can use make SDKCONFIG_DEFAULTS=yourboardconfig to build Lua RTOS with your own configuration

**Comment by thunderWhitecat** [comment]
Please, reopen if you need more assistance.
