### ISSUE TITLE
Where can I find the .bin file from the Whitecat console

### ISSUE THREAD

**Issue by MiLeG** [whitecatboard/Lua-RTOS-ESP32#196]
Hi!
When I run the Whitecat console and select a board it makes a custom .bin file that it flashes afterward, right? So where can I find the .bin file that is being flashed after I select a board type?
Thanks in advance!

**Comment by thunderWhitecat** [comment]
@MiLeG,

Add -d flag in the command line, to see the debug output. This shows which folders are used by wcc.

Example:

wcc -d -p ..... -erase

Output:

2018/10/01 09:58:11 AppFolder:  /Applications/The Whitecat Create Agent
2018/10/01 09:58:11 AppFileName:  /Applications/The Whitecat Create Agent/wcc
2018/10/01 09:58:11 AppDataFolder:  /Users/jaumeolivepetrus/.wccagent
2018/10/01 09:58:11 AppDataTmpFolder:  /Users/jaumeolivepetrus/.wccagent/tmp

Firmware files are stored in AppDataTmpFolder. In that folder you should see the flash_args file, with the files used to flash the device.

**Comment by MiLeG** [comment]
Much appreciated! I haven't got the time to check the syntax for a debug mode, but maybe it would be a nice thing to have these details somewhere on the readme just in case someone is curious.
