### ISSUE TITLE
SD driver does not compile

### ISSUE THREAD

**Issue by gruntcoder** [whitecatboard/Lua-RTOS-ESP32#20]
Recent changes to the SPI interface has broken the SD driver.

spi_transfer function signature has changed; the results is now error / success status, and the byte read is passed by reference.

If you haven't already fixed this then I have a version that is working (along with a few other small enhancements).  I can submit a pull request

**Comment by thunderWhitecat** [comment]
Perfect. Submit pull request if you can.

**Comment by thunderWhitecat** [comment]
Thanks for report this.

This has been solved in this commit: https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/345c3b251037633cf1f7393d10dfc4161fadce9d

**Comment by jolivepetrus** [comment]
Let me to close this issue. No feedback were provided.

**Comment by thunderWhitecat** [comment]
Let me to close this issue. No feedback were provided.
