### ISSUE TITLE
Whitecat Console binary

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#201]
Is the wcc program also for windows 32 Bit platform available?

**Comment by thunderWhitecat** [comment]
@lu1210,

Please try with http://downloads.whitecatboard.org/console/wcc32.exe.

I haven't a W32 platform to test.

**Comment by lu1210** [comment]
the link isn't reachable for me( error 404)

**Comment by thunderWhitecat** [comment]
@lu1210,

Sorry:

http://downloads.whitecatboard.org/console/windows/wcc32.exe

**Comment by lu1210** [comment]
It runs perfect :-)
