### ISSUE TITLE
ESP32-POE

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#205]
Since Olimex EVB and GATEWAY are supported, I was expecting that the POE version would work too. But it doesn't. (net.en.start hangs)
I'm not sure what var to replace to add the board, to create a pull request.

https://www.olimex.com/Products/IoT/ESP32/ESP32-POE/open-source-hardware

**Comment by thunderWhitecat** [comment]
@gjongenelen,

I don't have this board, but according to its schematic you should change the Ethernet config in this way: 

![image](https://user-images.githubusercontent.com/16651312/47710285-afc1f680-dc32-11e8-9562-f5471e75cce3.png)

**Comment by gjongenelen** [comment]
I proposed PR #208 with the correct pin-mapping.
