### ISSUE TITLE
Httpsrv.c LoadProhibited

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#209]
We're getting LoadProhibited errors in the http-server. It looks like the server is unable to close the client in https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/e414c76583a8208d3d5cab1acc645910f15f04ef/components/http/httpsrv.c#L1162.

Uncommenting lines 1162, 1165 and 1166 prevent the error occurring but make the http-server unusable when 10 requests has taken place. (socket error)
<img width="852" alt="screenshot 2018-11-05 at 11 59 18" src="https://user-images.githubusercontent.com/5789343/47994348-450d3100-e0f2-11e8-9040-968a43a22c99.png">

How can we solve this?

**Comment by thunderWhitecat** [comment]
@gjongenelen,

Thanks for report this. It seems that was a esp-idf related issue. Please, try again with commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/3dbcd2b13772795ce0a57a2725ff0461401c6d11, which is updated to las esp-idf commit.

Proceed as follow:

make clean
make upgrade-idf
make flash

Please, take note that probably you are required to execute also "/usr/bin/python -m pip install --user -r /Users/jaumeolive/esp-idf/requirements.txt" to update the required requirements.

**Comment by thunderWhitecat** [comment]
@gjongenelen,

Any feedback on this issue?.

**Comment by gjongenelen** [comment]
Couldn’t test it yet. Had to switch to c++ because I had to deliver the prototype. 
Will test it when I have the time

**Comment by thunderWhitecat** [comment]
@ctshh,

Issue closed, as we don't have any feedback.
