### ISSUE TITLE
SD driver should have more configuration options

### ISSUE THREAD

**Issue by gruntcoder** [whitecatboard/Lua-RTOS-ESP32#21]
The SPI pins (more than just the select pin) should be available as makemenu configuration options.

If you accept this then I can fix and submit a pull request.

**Comment by thunderWhitecat** [comment]
Thanks for report this.

This is done in our last commit. Please see https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/dbfa35bf27606be961cc7655daaa585e3595277c

**Comment by thunderWhitecat** [comment]
Let me to close this issue. No feedback were provided.
