### ISSUE TITLE
DHT22 wrong result if temperature is less then 0 grad celsius

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#212]

**Comment by lu1210** [comment]
If temperature is e.g. -0.1 °C DHT22 returns 3276.9.

**Comment by thunderWhitecat** [comment]
@lu1210,

Thanks for report this. It should be solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/d6a22aea872e3a64fbf62d1990e8250562f3415e.

**Comment by lu1210** [comment]
patch is successfully verified
