### ISSUE TITLE
Issue staring ssh server

### ISSUE THREAD

**Issue by hexmaster111** [whitecatboard/Lua-RTOS-ESP32#214]
On a fresh install, going and editing the config.lua to enable ssh and WiFi setting the password and rebooting, resulted in this 

Lua RTOS beta 0.1. Copyright (C) 2015 - 2018 whitecatboard.org

build 1543881471
commit 2703dd1ec8dfcb6ae9bcb38d4b48fddd3bdbfa2b
Running from ota_0 partition
board type ESP32COREBOARD
cpu ESP32 rev 1 at 240 Mhz
spiffs start address at 0xf000, size 512 Kb
spiffs mounted on /

Lua RTOS beta 0.1 powered by Lua 5.3.4

Executing /system.lua ...
Starting wifi ...
Starting sntp client ...
Starting ssh server ...
lua: /system.lua:114: attempt to index a nil value (field 'ssh')
stack traceback:
        /system.lua:114: in main chunk
        [C]: in ?
Executing /autorun.lua ...

with a failure to connect via ssh.

**Comment by thunderWhitecat** [comment]
@hexmaster111,

You are using a firmware with SSH support disabled. You must build Lua RTOS and enable SSH support.

$ make menuconfig

![image](https://user-images.githubusercontent.com/16651312/49730276-29a8bf00-fc78-11e8-8e3f-7b2302fb7c96.png)

$ make flash
