### ISSUE TITLE
small issues in /examples/lua/bme280-tft.lua

### ISSUE THREAD

**Issue by elsbiet** [whitecatboard/Lua-RTOS-ESP32#217]
line 23 should read

s1 = sensor.attach("BME280", i2c.I2C0, 0x76, 400)

instead of

s1 = sensor.attach("BME280", i2c.I2C0, 400, 0x76)

**Comment by elsbiet** [comment]
likewise in the same file

line 16 should read

gdisplay.setfont(gdisplay.FONT_UBUNTU16)

instead of

gdisplay.setfont(gdisplay.UBUNTU16_FONT)

**Comment by thunderWhitecat** [comment]
@spellauge,

Thanks to report this. Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/da4b57c45a3068de9e2c0e3d63b13ba3ac71a60f.
