### ISSUE TITLE
docu - https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/MQTT-module

### ISSUE THREAD

**Issue by elsbiet** [whitecatboard/Lua-RTOS-ESP32#218]
client:subscribe(topic, qos, callback):

after looking into the source code, it seems to me that the callback function should be specified as
callback(message_len, message [, topic_len, topic])

**Comment by thunderWhitecat** [comment]
@spellauge,

Thanks for report this. MQTT wiki has been updated (https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/MQTT-module).
