### ISSUE TITLE
nvs documentation

### ISSUE THREAD

**Issue by elsbiet** [whitecatboard/Lua-RTOS-ESP32#219]
please correct https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/NVS-Module

nvs.read(namespace, key)
..
replace 
'Returns: nothing, or an exception.'
by
'Returns: linked value, or an exception.'

and maybe you want to mention the function nvs.exists(namespace, key) returning true or false.

**Comment by thunderWhitecat** [comment]
@spellauge,

Thanks for report this. Wiki updated as proposed.
