### ISSUE TITLE
MQTT does not support encrypted transmission

### ISSUE THREAD

**Issue by the0ne** [whitecatboard/Lua-RTOS-ESP32#23]
The current MQTT implementation relys on OpenSSL being available at compile time.
The Problem is that OpenSSL is not used for the creation of the lua_rtos binary but mbedTLS is being used.
For this reason the MQTT implementation needs to be ported to mbedTLS as unencrypted MQTT is not an option except when using a local MQTT broker because of MITM-Attacks, Replay Attacks, etc.

**Comment by thunderWhitecat** [comment]
@the0ne, thanks for report this.

In the coming weeks a public mqtt server will be available at whitecatboard.org, where users who are evaluating Lua RTOS will be able to perform mqtt tests in both plain and encrypted transmissions.

**Comment by the0ne** [comment]
If it is of any help I can offer access to a broker that is set up already, reachable 24/7 and offering encrypted authenticated connections.

**Comment by thunderWhitecat** [comment]
Perfect!

Yes, this would be a great help to us. You can contact me at admin@whitecatboard.org for more details.

**Comment by the0ne** [comment]
I managed to fix several issues and to "port" the SSLSocket code to the mbedTLS openssl abstraction layer. So basically encrypted MQTT works, though not with all security features like client certs or full server validation. There's some more issues that need to be checked, tough - e.g. client ids when using several threads.

**Comment by thunderWhitecat** [comment]
Gonna look into it, but at the moment I'm slightly distracted by The Whitecat IDE.

Can you make a pull request for test it and help you to complete the work?

**Comment by the0ne** [comment]
see #30 commit bfaca2f6c818fe54673da22c07d6b9c7fc659061
