### ISSUE TITLE
Wiki https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/NEOPIXEL-module

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#230]
Sample:
-- Setup a NEOPIXEL bus formed by 6 WS2812B leds, connected to GPIO14
neo = neopixel.**setup**(neopixel.WS2812B, pio.GPIO14, 6)  **<-- attache, not setup**

-- Set color for pixel 0 (pure red)
neo:setPixel(0, 255, 0, 0)

-- Set color for pixel 1 (pure green)
neo:setPixel(**0**, 255, 0, 0) **<-- 1 not 0**

-- Set color for pixel 2 (pure white)
neo:setPixel(**0**, 255, 255, 255) **<-- 2 not 0**

All sample use setup, must be attach

**Comment by thunderWhitecat** [comment]
@Mynogs,

I have just updated the wiki:

https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/NEOPIXEL-module

Can you review it?

**Comment by Mynogs** [comment]
This is still wrong in all samples:
-- Set color for pixel 1 (pure green)
neo:setPixel(**1**, 255, 0, 0) <-- 1 not 0

-- Set color for pixel 2 (pure white)
neo:setPixel(**2**, 255, 255, 255) <-- 2 not 0

**Comment by Mynogs** [comment]
Wrong button... sorry.

**Comment by thunderWhitecat** [comment]
@Mynogs,

Solved!

**Comment by Mynogs** [comment]
Yes!
