### ISSUE TITLE
Function parameter wrong for net.wf.setup(net.wf.mode.AP...

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#233]
Currently:
net.wf.setup(net.wf.mode.AP, [powersave, channel, hidden])
Should be:
net.wf.setup(net.wf.mode.AP, ssid, password, [powersave, channel, hidden])

**Comment by the0ne** [comment]
@Mynogs yes, the wiki is wrong about this
I have updated it [here](https://github.com/the0ne/Lua-RTOS-ESP32/wiki/Net-module#netwfsetupnetwfmodeap-ssid-password-powersave-channel-hidden)

**Comment by Mynogs** [comment]
Fine!
