### ISSUE TITLE
LoRaWAN Node - OTA How to avoid join after sleep o power on ?

### ISSUE THREAD

**Issue by ssachse** [whitecatboard/Lua-RTOS-ESP32#248]
I want to use OTA, but I want to minimize the join requests like proposed by TTN. Is there a way to store Nwskskey, Appskey and Framecounter. somewhere ? And to check wether the device is already joined ? Thanks

**Comment by thunderWhitecat** [comment]
@ssachse,

Well, all is ready in our Lora Stack, but never has been implemented. I need to recover my notes on that ...
Can you wait until next Monday?

**Comment by ssachse** [comment]
Sure, thanx I'd appreciate any info on that lora stack.
Si hiciste chido trabajo con este proyecto. Gracias!
cheers
Stefan

**Comment by thunderWhitecat** [comment]
@ssachse,

Implemented in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/69fec0b4deb50a3fc0142f1f683e364e7bede005. Please, note that avoid joining from a power on, or reset state, is not possible for security reasons (explained in commit message).

**Comment by thunderWhitecat** [comment]
@ssachse,

Reopen the issue in case you need more assistance.
