### ISSUE TITLE
Restore files system

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#257]
By mistake, I have deleted some important files on my board.
I tried with wcc -ffs: to restore the files. Nothing happens, the old content is preserved. Also -erase: does not help.
How can I reset a board completely?

**Comment by thunderWhitecat** [comment]
@Mynogs,

Something connected to an strapping pin? (12, 0, 2, 4, 15, 5)

**Comment by the0ne** [comment]
@Mynogs were you able to fix this issue?

**Comment by Mynogs** [comment]
Nothing connected to the strapping pin. I remove the ESP32 board from the base board.

**Comment by the0ne** [comment]
Ok, thanks for that information!
