### ISSUE TITLE
 how to stop a stepper motor?

### ISSUE THREAD

**Issue by ar055** [whitecatboard/Lua-RTOS-ESP32#270]
Is it possible to stop the stepping motor prematurely and find out the number of steps it has passed?

**Comment by the0ne** [comment]
in the [wiki](https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/STEPPER-module) it's visible that this is currently not possible and the [source](https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/master/components/lua/modules/hw/stepper.c) confirms that there currently is no interface to stop a stepper.

**Comment by ar055** [comment]
Is this feature expected to be added?

**Comment by thunderWhitecat** [comment]
@ar055, @the0ne,

Yes, this function will be added soon.
I'm on vacation until next Tuesday.

**Comment by thunderWhitecat** [comment]
@ar055, @the0ne,

Done in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/021cd2b57ab1e76f7a6a1d60479012e4b02735be.
