### ISSUE TITLE
RMT on a Sparkfun Thing giving error

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#273]
When using neopixel (which uses RMT) connected to a Sparkfun Thing board, I get the following error on the console:

```
/ > neo = neopixel.attach(neopixel.WS2812B, pio.GPIO19, 24)
E (365871) rmt: rmt_driver_uninstall(677): No RMT driver for this channel
/ > 
```
After this, the module still works (I suppose through bitbang, but can't be sure). I'm not sure what the channel is, nor where it can be configured. I only left the `CONFIG_LUA_RTOS_LUA_USE_RMT=y` in sdkconfig.

Note, building with RMT disabled fails with linking errors.

**Comment by thunderWhitecat** [comment]
@xopxe,

Thanks for report this. Don't worry, in your case neopixel driver uses RMT. This is a problem with the esp-idf, in which we don't have an API to known if RMT driver is yet installed for a channel, but in our  driver we need to ensure that driver is uninstalled, but first time esp-idf shows an error.

To solve that we change the esp-idf log level when calling rmt_driver_uninstall. Now message is notr showed.

Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/db4ac477a05a4cf0b1bd8915d213c9a7c882f7ec.
