### ISSUE TITLE
console io.read doesn't allow backspace

### ISSUE THREAD

**Issue by technomancy** [whitecatboard/Lua-RTOS-ESP32#276]
Normally when connected over the serial port, backspace works fine. However, when you call `io.read`, it starts reading input in a different way where backspace seems to have no effect.

Curiously, the arrow keys do work in this mode, but it seems to be in overwrite mode. So you can get the same effect (if you're aware of the workaround) but it is disorienting.

**Comment by the0ne** [comment]
Hi @technomancy,

please don't try to use io.read while connected over serial port.
As far as I have seen it's mainly used by [wcc ](https://github.com/whitecatboard/whitecat-console/) to transfer files.
I don't think it's meant for interactive use.
