### ISSUE TITLE
Lua-RTOS-Kendryte(K210)?

### ISSUE THREAD

**Issue by Bazmundi** [whitecatboard/Lua-RTOS-ESP32#279]
If Lua-RTOS-X is running on [freertos](https://github.com/kendryte/kendryte-freertos-sdk), then ...?

Why not, there was a micropython port (or at least an openmv port ;).

**Comment by the0ne** [comment]
Hi @Bazmundi,

as the name suggests, **Lua**-RTOS is about _Lua_.
Not _Python_. Not _MicroPython_. Not _OpenMV_.

In case of issues please feel free to open another issue.

**Comment by Bazmundi** [comment]
It's a feature request to port lua-rtos to k210. Thanks for your critical thinking. Unclose it to open up the debate.

**Comment by the0ne** [comment]
> It's a feature request to port lua-rtos to k210. Thanks for your critical thinking. Unclose it to open up the debate.

@Bazmundi thanks a lot for clarification!
:-)

**Comment by thunderWhitecat** [comment]
@Bazmundi, @the0ne,

Debate is open! Ho wants to start?

**Comment by the0ne** [comment]
@Bazmundi as you want to run Lua-RTOS on Kendryte(K210), can you create a PR containing the required board config, etc.?

**Comment by thunderWhitecat** [comment]
@Bazmundi, @the0ne,

First, anyone has middle / low-level knowlegde on this platform?

**Comment by the0ne** [comment]
I have never before even heard the name.

**Comment by Bazmundi** [comment]
Yep. My first time through this deep in the process but happy to give it a
crack. Have you a link to example process?

**Comment by ar055** [comment]
we are talking about?
https://github.com/kendryte/kendryte-freertos-sdk

**Comment by Bazmundi** [comment]
Porting lua-rtos to kendryte

**Comment by ar055** [comment]
> Porting lua-rtos to kendryte

And Torch7 please! :)

**Comment by ar055** [comment]
see RT-Thread  this China project.
https://github.com/RT-Thread/rt-thread/tree/master/bsp/k210
I've set it to MAX Bit, IMHO its alpha stage.

**Comment by ar055** [comment]
![image](https://user-images.githubusercontent.com/49328380/68960977-4cc1e400-07e2-11ea-8bae-150c03c6430b.png)

**Comment by Bazmundi** [comment]
@ar055 This is FANTASTIC!  Have you also seen though some of the "threaded" lua approach of [whitecat](https://whitecatboard.org/software/lua-rtos/) implementation?

**Comment by ar055** [comment]
> @ar055 This is FANTASTIC! Have you also seen though some of the "threaded" lua approach of [whitecat](https://whitecatboard.org/software/lua-rtos/) implementation?

Hm... Lua RTOS can execute Lua functions into FreeRTOS native threads. Unlike Lua coroutines, threads are scheluded by the operating system, allowing to run Lua programs in real time.

**Comment by the0ne** [comment]
Personally I don't have any K210 available.
Feel free to reopen in case you got some more information and want to let others know.
Thanks!
