### ISSUE TITLE
URL to esp-idf setup for Mac OS has changed

### ISSUE THREAD

**Issue by jcwren** [whitecatboard/Lua-RTOS-ESP32#28]
Lua-RTOS-ESP32/README.md, line 87, the URL points to https://github.com/espressif/esp-idf/blob/master/docs/macos-setup.rst, which 404's.

Current docs are at http://esp-idf.readthedocs.io/en/latest/get-started/macos-setup.html or https://github.com/espressif/esp-idf/blob/master/docs/get-started/macos-setup.rst

**Comment by thunderWhitecat** [comment]
Thanks for report this.

README.md links changed to new URLS for all platforms: Mac, Linux, Windows.
