### ISSUE TITLE
Software reset functionality

### ISSUE THREAD

**Issue by xopxe** [whitecatboard/Lua-RTOS-ESP32#285]
We added a ```os.reset()``` call to restart the board (it's just a call to esp_restart())

https://github.com/xopxe/Lua-RTOS-ESP32/commit/b57be16314e271d85fe8df71570ae4d2c548552c

Is it useful?

**Comment by the0ne** [comment]
Hi @xopxe,

please have a look at the lua function os.exit() which uses os_exit in the same file [`loslib.c`](https://github.com/whitecatboard/Lua-RTOS-ESP32/blob/master/components/lua/src/loslib.c).
It calls esp_restart but before it takes care of backtrace handling.

**Comment by lu1210** [comment]
Hi, what is the difference to the cpu.sleep(0) function?

**Comment by xopxe** [comment]
Oh, I grepped esp_restart and somehow missed that. 
There's a further comment, so feel free to close this whenever you want.

**Comment by the0ne** [comment]
@lu1210 more or less should be the same outcome but the reset reason will be different
@xopxe closing this
