### ISSUE TITLE
Wrong output by os:locks()

### ISSUE THREAD

**Issue by lu1210** [whitecatboard/Lua-RTOS-ESP32#286]
GPIO16 & GPIO17 are assigned to I2C1 interface, but os.locks() shows I2C0 interface.

i2c.setpins(i2c.I2C1,pio.GPIO16,pio.GPIO17)
i2c.setpins(i2c.I2C0,pio.GPIO22,pio.GPIO21)

i2c0 = assert(i2c.attach(i2c.I2C0,i2c.MASTER,100000),'I2C0 Iface not found')
i2c1 = assert(i2c.attach(i2c.I2C1,i2c.MASTER,100000),'I2C1 Iface not found')
os.locks()
gpio
  gpio1 locked by uart0 (TX)
  gpio3 locked by uart0 (RX)
  gpio16 locked by i2c0 (SDA)   <--- gpio16 is assigned to the i2c1 interface
  gpio17 locked by i2c0 (SCL)   <--- gpio17 is assigned to the i2c1 interface
  gpio21 locked by i2c0 (SCL)
  gpio22 locked by i2c0 (SDA)

**Comment by thunderWhitecat** [comment]
@lu1210,

Thanks for report this. Solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/c5971ee8dbd0b4be7f66a5b6676800d3ef84ca74.
