### ISSUE TITLE
How i can to add math string and tables modules?

### ISSUE THREAD

**Issue by SergeySlyusarEZlo** [whitecatboard/Lua-RTOS-ESP32#293]
Hello friend!! Grant job!! I want to use this lib with math, string and tables modules. How can i add math string and tables modules support?

**Comment by the0ne** [comment]
All included. Just use it.

**Comment by thunderWhitecat** [comment]
@SergeySlyusarEZlo, @the0ne,

Sorry for the delay in my answer. Just coming from the vacation period!.

As commented by @the0ne, standard Lua 5.3.4 math, string and table functions are included in Lua RTOS.

Just use it.

Issue is closed, please, reopen in case you need more assistance.
