### ISSUE TITLE
I2C Unexpected byte on the bus

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#296]
I have an ESP32 (master) connected to an ATmega88 (slave) via I2C.
I write this program on the ESP32:
```
  block.d = i2c.attach(i2c.I2C0, i2c.MASTER, 100000)
...
  block.d:start()
  block.d:address(0x08, false)
  block.d:write(123)
  block.d:start()
  block.d:address(0x08, true)
  local read1, read2, read3 = block.d:read(), block.d:read(), block.d:read()
  block.d:stop()
  print(read1, ' ', read2, ' ', read3)
```
When I trace the bus with the logic analyzer I see this:

![grafik](https://user-images.githubusercontent.com/11896946/63596429-86a49500-c5bb-11e9-84ee-c8d0530cba87.png)

Each time a byte is fetched from the slave, the value is incremented. You can see that four bytes are fetched, but in the program there are only three `blocks.d:read()`. Why is the reason for this behavior?
It looks like the fourth byte is send after `block.d:stop()`.

**Comment by the0ne** [comment]
Confirmed. Fixed by #312
Please note that you will need to modify your lua code as well:
```
  block.d = i2c.attach(i2c.I2C0, i2c.MASTER, 100000)
...
  block.d:start()
  block.d:address(0x08, false)
  block.d:write(123)
  block.d:start()
  block.d:address(0x08, true)
  local read1, read2, read3 = block.d:read(3)
  block.d:stop()
  print(read1, ' ', read2, ' ', read3)
```
