### ISSUE TITLE
Using sockets and redis produce corrupt heap exeption

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#317]
Hello all!

I created a version for the M5STACK with my esp development environment. I have the latest versions of all tools and source code (I hope ...).
When I use redis.lua I get the following exeption:

```
CORRUPT HEAP: multi_heap.c:432 detected at 0x3fffbc10
abort() was called at PC 0x4009a3e3 on core 0

ELF file SHA256: 964a42ed5b60393f126608fd9c9af86e6253cca4e6240e4f290f9265e1903335

Backtrace: 0x40090f6f:0x3fffc4a0 0x400912b1:0x3fffc4c0 0x4009a3e3:0x3fffc4e0 0x4009a74b:0x3fffc500 0x40085998:0x3fffc530 0x400859dc:0x3fffc550 0x40085d55:0x3fffc570 0x40086f61:0x3fffc590 0x4000beaf:0x3fffc5b0 0x4009747e:0x3fffc5d0 0x40097664:0x3fffc5f0 0x40085dc6:0x3fffc610 0x40085ed6:0x3fffc630 0x4000bde5:0x3fffc650 0x40001ef0:0x3fffc670 0x4022f68b:0x3fffc690 0x4022f72d:0x3fffc6c0 0x401381c9:0x3fffc6e0 0x401384dd:0x3fffcf10 0x401385b9:0x3fffcf30 0x40137b38:0x3fffcf50 0x40137d6e:0x3fffcf80 0x40137d95:0x3fffcfa0 0x401491c8:0x3fffcfc0 0x40138044:0x3fffcfe0 0x401380e0:0x3fffd810 0x40137b38:0x3fffd830 0x401467c1:0x3fffd860 0x40137a5d:0x3fffd8d0 0x40137d2f:0x3fffd8f0 0x4013773d:0x3fffd910 0x40137dfc:0x3fffd990 0x4014833c:0x3fffd9d0 0x401484d2:0x3fffd9f0 0x40137b38:0x3fffda10 0x401467c1:0x3fffda40 0x40137d75:0x3fffdab0 0x40137d95:0x3fffdad0 0x40148681:0x3fffdaf0 0x4013773d:0x3fffdb10 0x40137f00:0x3fffdb90 0x40149215:0x3fffdbc0 0x4012a278:0x3fffdbf0 0x401341bf:0x3fffdc10 0x40121f16:0x3fffdc30

```
I connect to my home WiFi network. After I get a connection (net.connected() == true) I do 
client = redis.connect{host = '192.168.1.3', port = 6379}. The the exeption occures.

I use:
Ubuntu 18.04LTS
crosstool-ng-1.22.0-80-g6c4433a
Lua-rtos * master e2267313 [origin/master]
Lua RTOS beta 0.1. Copyright (C) 2015 - 2018 whitecatboard.org
build 1574157211
commit e2267313356c6324090933a07cad7cb9f4bf1494
REDIS: redis-lua 2.0.5-dev

I have attached the Lua code of the application. Please note: the code is generatet by my p+ tool.

[remote.zip](https://github.com/whitecatboard/Lua-RTOS-ESP32/files/3867534/remote.zip)

I do not understand the Lua-RTOS enough to find such a issue. Can someone help me?

**Comment by the0ne** [comment]
I assume that what you saw was memory issues from the used ESP-IDF.
Let's hope that this will be gone once the ESP-IDF has been updated. See #402
