### ISSUE TITLE
Feature request: Implement WAV-playback

### ISSUE THREAD

**Issue by Mancom-BWE** [whitecatboard/Lua-RTOS-ESP32#330]
It would be great if something like [https://nodemcu.readthedocs.io/en/master/modules/pcm/](https://nodemcu.readthedocs.io/en/master/modules/pcm/) could be implemented. There are a lot of possible applications:

- connected to a SIM800L or similar module, one can transmit voice messages (status, alarm, ...) which are better recognised than SMS (which can easily be overlooked)
- acustic feedback for devices without display
- Wifi-Speaker
- ...

**Comment by the0ne** [comment]
Feel free to create a PR. Thanks!
