### ISSUE TITLE
SPI function readwrite resend (echo) received bytes

### ISSUE THREAD

**Issue by Mynogs** [whitecatboard/Lua-RTOS-ESP32#337]
If I use the SPI readwrite function:

```
  device:select()
  local recv = device:readwrite(
    (address >> 16) & 0xFF,
    (address >> 8) & 0xFF,
    address & 0xFF,
    0xFF, -- Dummy
    0 -- Read byte 0
  )
  device:deselect()
```

Date is send and receive correcty. But all bytes I received are send again during the deselect call.

![All](https://user-images.githubusercontent.com/11896946/75053866-483c5400-54d2-11ea-8709-f2b46bfa9bb4.png)

You can see the the unexpected second packet.

This is the first packet:
![Send1](https://user-images.githubusercontent.com/11896946/75053945-6904a980-54d2-11ea-83e3-e63abb1d423a.png)

This is the unexpected second packet:
![Send2](https://user-images.githubusercontent.com/11896946/75053979-791c8900-54d2-11ea-8df3-c868a9e051a6.png)

I think the bug is here (spi.c:314):

  ```
if (withread) {
        // Flush buffer
        if ((error = spi_bulk_rw(spi->spi_device, spi->len, spi->buff))) {
            goto exit;
        }
         spi->len = 0; <<<<< Missing, so deselect send the buffer again
```

In the moment I am not able to verify this. So please verify my fix.

**Comment by the0ne** [comment]
If you create a PR, then travis (automated build system) should be started by github.
I don't know if you can access the binaries that are built by travis - but you could try that to get a binary.

**Comment by Mynogs** [comment]
I checked the change. This solves the problem.

**Comment by the0ne** [comment]
Fantastic, thanks a lot for providing and testing the fix!
So did it work to have travis build the binary and use that to flash your board?
Or did you generate the binary the "classic" way?

**Comment by Mynogs** [comment]
I use the classic way. I have dedicated Linux VM only for the ESP32 and Lua RTOS.
