### ISSUE TITLE
Copy and Paste -  problems with code indentation

### ISSUE THREAD

**Issue by stexniolo** [whitecatboard/Lua-RTOS-ESP32#344]
Hello to everybody,
I'm writing some Lua code on _Visual Studio Code_ on my pc. I noticed that when I go to paste the written code on my _Whitecat board_, it doesn't indent well. This is the result:
![Schermata da 2020-04-15 23-01-07](https://user-images.githubusercontent.com/53082287/79388436-9bc89c80-7f6d-11ea-999d-9ddf3b3bd55c.png)

Is there a better way to transfer the written code on the board instead of just copying and pasting?
I'm using _picocom_ to connect to the Lua RTOS console.

Many Thanks.

**Comment by the0ne** [comment]
I was experiencing the same issue when pasting.
So a hotkey as been added to the editor quite a while ago to disable (and re-enable) indenting.
You can find it in the editor's help. I believe it's [Ctrl]+[T]

As an alternative to using the clipboard, try uploading files using the [whitecat console](https://github.com/whitecatboard/whitecat-console) which can be downloaded [here](https://github.com/whitecatboard/Lua-RTOS-ESP32#method-1-get-a-precompiled-firmware).

**Comment by stexniolo** [comment]
with _[Ctrl]+[T]_ before pasting the problem has been solved!
Thank you very much.

**Comment by the0ne** [comment]
Welcome ^^
