### ISSUE TITLE
M5StickC with LuaRTOS

### ISSUE THREAD

**Issue by Azzeccagarbugli** [whitecatboard/Lua-RTOS-ESP32#352]
Hi everybody,

I was looking for a board to use for my project and I found out this [one](https://m5stack.com/collections/m5-hat/products/m5stickc-development-kit-with-hat).

This board is based on the chip ESP32 Pico and I was wondering if I could install **LuaRTOS** on it.

I know that there is the [guide](https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/How-to-add-a-new-board) to flash the firmware but I don't know if after the installation, everything will work properly, above all the display and the other sensors _(speaker and temperature)_ provided within the bundle.

Thanks in advance!

**Comment by the0ne** [comment]
Personally I don't have any M5StickC available.
Feel free to reopen in case you find some more information and want to let others know.
Thanks!
