### ISSUE TITLE
GSM , 2G and LTE support

### ISSUE THREAD

**Issue by schmeckm** [whitecatboard/Lua-RTOS-ESP32#370]
Does the development environment support GSM support like tinygsm?
See example:
https://github.com/vshymanskyy/TinyGSM
It’s fundamental for IoT that this capability is supported

Markus

**Comment by the0ne** [comment]
I have already managed to integrate something like this, maybe it even was tinygsm. Don't remember exactly.

I had integrated the full networks interface. So *everything* was working as usual a after opening the GSM connection. All socket stuff working properly.
