### ISSUE TITLE
Failed to build on Ubuntu 20

### ISSUE THREAD

**Issue by KernelErr** [whitecatboard/Lua-RTOS-ESP32#379]
Hi, when I tried to build this project after finishing the first steps. I ran into some errors with esp-idf. Here are some errors I met:

- Should use print as a function in Python3 (boards/selection.py and gen_part.py)
- Unsupported version of esp tool, same as #350 
- Multiple undeclaration errors in several components of esp-idf

So would you like to provide a docker image to build it or some updates? I'll very much appreciate that. Thanks.

**Comment by the0ne** [comment]
This project is currently not based on the latest ESP-IDF, sorry.

**Comment by TotallyNotSethP** [comment]
A docker image would be really nice... building this project is unnecessarily complicated with many steps not documented very well

**Comment by the0ne** [comment]
Yes maybe that would be nice 🤔
But for many people it works to build as documented 🙂
