### ISSUE TITLE
Raspberry Pi Pico support?

### ISSUE THREAD

**Issue by ShoesForClues** [whitecatboard/Lua-RTOS-ESP32#383]
Are there any plans to support the new Raspberry Pi Pico?
https://www.raspberrypi.org/documentation/pico/getting-started/

**Comment by panchalnikunj** [comment]
https://www.youtube.com/channel/UCA4j-J-TFW_9Dt4iTwIjtYQ

Visit this channel for raspberry pi pico projects.

**Comment by tochinet** [comment]
After one year without a valid response, the answer is obviously no. Porting software from ESP32 to RPi is not simple at all, RPi usually is running Linux and ESP32 runs FreeRTOS.

**Comment by ShoesForClues** [comment]
> After one year without a valid response, the answer is obviously no. Porting software from ESP32 to RPi is not simple at all, RPi usually is running Linux and ESP32 runs FreeRTOS.

FreeRTOS has already been ported to the Pi Pico. The RP2040 isn't restrained to a specific OS and neither is the ESP32.

**Comment by mgliewe** [comment]
The rp2040 is a much more memory restricted, I assume LuaRTOS would have to be stripped down a lot. Also, the build system is quiet ESP-IDF specific.

You might want to take a look at https://github.com/kevinboone/luapico instead.

**Comment by the0ne** [comment]
Feel free to reopen in case of questions.
