### ISSUE TITLE
question: {DEVADDR, NWKSKEY, APPSKEY} in  ./components/lora/node/lmic/lora_lmic.c 

### ISSUE THREAD

**Issue by elsbiet** [whitecatboard/Lua-RTOS-ESP32#395]
why not store {DEVADDR, NWKSKEY, APPSKEY} in persistent memory (to minimize the number of join requests to 1) after a device has successfully  joined ?

**Comment by elsbiet** [comment]
no response in 3 months - assuming that this project is dead.

**Comment by the0ne** [comment]
There's not too much activity around LORA currently in this project.
I don't have any devices with LORA support.
