### ISSUE TITLE
version 9.0.0 FreeRTOS

### ISSUE THREAD

**Issue by edbek** [whitecatboard/Lua-RTOS-ESP32#4]
whether it is possible to transfer the project to the latest version 9.0.0 FreeRTOS ?

**Comment by thunderWhitecat** [comment]
Lua RTOS for ESP32 it's working on top espressif esp-idf. In ESP32 FreeRTOS port is a heavily modified version of FreeRTOS V8.2.0 for give multicore support, and is maintained by Espressif.

Some of FreeRTOS V9.0.0. functions have been back-ported to ESP32 port, such as local storage pointers, used by esp-idf and Lua RTOS.

In other Lua RTOS supported platforms migration to Free RTOS V9.0.0. is planned for 2017 2Q.
