### ISSUE TITLE
How to build Lua RTOS with the screen module

### ISSUE THREAD

**Issue by TotallyNotSethP** [whitecatboard/Lua-RTOS-ESP32#407]
I see from [this wiki page](https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/SCREEN-module) that there is a screen module which i really want to use for my project. However, no prebuilt board OSes include support and there doesn't appear to be an option for it in the build settings. So how do you access it?

**Comment by TotallyNotSethP** [comment]
On a related note, is there any chance the module will support more chipsets in the future?

**Comment by TotallyNotSethP** [comment]
`make menuconfig` has no screen module option:
![image](https://user-images.githubusercontent.com/14851383/166344673-26ee8f50-594d-4433-b0c0-ee41b5eece4c.png)

**Comment by the0ne** [comment]
Maybe check the following, seems the wiki was not renamed:
https://github.com/whitecatboard/Lua-RTOS-ESP32/wiki/GDISPLAY-module

**Comment by TotallyNotSethP** [comment]
you just saved my life thank you :)
