### ISSUE TITLE
Olimex ESP32 EVB firmware has two devices using the same pins

### ISSUE THREAD

**Issue by TotallyNotSethP** [whitecatboard/Lua-RTOS-ESP32#408]
The SPI display uses pins 15 and 2 but so does the SD card so you can't run both at the same time...
![image](https://user-images.githubusercontent.com/14851383/166627405-67e59baa-bcd4-4a2b-add4-ded7fb73d4fd.png)
![image](https://user-images.githubusercontent.com/14851383/166627422-c34c7269-42d8-4bb9-83b8-bdc1fd5b3d34.png)

**Comment by the0ne** [comment]
Maybe just reconfigure it to whatever you use on your hardware.

**Comment by TotallyNotSethP** [comment]
How do I reconfigure it?

**Comment by the0ne** [comment]
Not an issue, closing.
