### ISSUE TITLE
Running gdisplay.attach in a file puts garbage on top rows of tft screen

### ISSUE THREAD

**Issue by TotallyNotSethP** [whitecatboard/Lua-RTOS-ESP32#418]
![PXL_20220830_051018746 MP](https://user-images.githubusercontent.com/14851383/187355046-f3414fda-a7ae-4dd4-9240-fc3e437d33a4.jpg)

This doesn't occur when running `gdisplay.attach` in a regular file.

**Comment by TotallyNotSethP** [comment]
Also you can't clear the garbage unless you reboot the system

**Comment by the0ne** [comment]
I don't have such a piece of hardware. So I can't reproduce.

**Comment by TotallyNotSethP** [comment]
Ok a temporary workaround is to run `gdisplay.attach` in a regular file, then `dofile` from `system.lua`

**Comment by TotallyNotSethP** [comment]
Update: it now shows garbage no matter what file you run the attach command in...

**Comment by TotallyNotSethP** [comment]
This might be the same issue as https://forum.lvgl.io/t/random-colored-lines-in-display-gc9a01/4545

**Comment by TotallyNotSethP** [comment]
It works fine from the command line

**Comment by TotallyNotSethP** [comment]
Oh, and it works now... very inconsistent behaviour

**Comment by TotallyNotSethP** [comment]
In a shocking new development, i cant put anything in the top two rows anymore. {0,0} is {0,2} on the actual screen

**Comment by TotallyNotSethP** [comment]
I suspect this may just be an issue with the buffer being two rows down from where it should be

**Comment by TotallyNotSethP** [comment]
@the0ne Do you know where the interface code is for the ST7735 1.44" green tab... I want to try to fix this issue

**Comment by the0ne** [comment]
That would be
```
components/sys/drivers/st7735.c
components/sys/drivers/st7735.h
```
I guess.

**Comment by the0ne** [comment]
@TotallyNotSethP did you finally find a solution?
Feel free to reopen in case of questions or create a PR if you want to share your solution with others.
