### ISSUE TITLE
ESP32-C3 Support

### ISSUE THREAD

**Issue by rrrnld** [whitecatboard/Lua-RTOS-ESP32#421]
Hi,

I couldn't find an answer by searching through the source code. Is the ESP32-C3 supported, or are there any plans to do so?

Thanks a lot!

**Comment by the0ne** [comment]
Concretely there's plans to upgrade the ESP-IDF.
Do you have some idea about what version of the ESP-IDF is required to support the [ESP32-C3](https://www.espressif.com/en/products/socs/esp32-c3)? A quick seach didn't bring up the results for me.

**Comment by rrrnld** [comment]
I'm not sure, but current `HEAD` contains a couple of references to it: https://github.com/espressif/esp-idf/search?q=esp32-c3

**Comment by the0ne** [comment]
Personally I don't have any C3 available.
Feel free to reopen in case you find some more information and want to let others know.
Thanks!
