### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by progerstar** [whitecatboard/Lua-RTOS-ESP32#425]
Is this project abandoned? Is anyone maintaining an active fork?

**Comment by the0ne** [comment]
It's actively _used_ 😃

**Comment by the0ne** [comment]
The project isn't abadoned.
Some of the recently active forks can be found using [[Insights]](https://github.com/whitecatboard/Lua-RTOS-ESP32/pulse) -> [[Network]](https://github.com/whitecatboard/Lua-RTOS-ESP32/network)
