### ISSUE TITLE
load() gives nil

### ISSUE THREAD

**Issue by progerstar** [whitecatboard/Lua-RTOS-ESP32#427]
load("print(2)") gives nil. why?
and what are the additional parameters: chunkname (default value = "?") and mode = luaL_optstring(L, 3, "bt") ?

```
	local cmd = "your command here"
	print("now executing "..cmd)
	local function dostring (x) return assert(load(x), "")() end
	print(dostring(cmd))
```

_Originally posted by @the0ne in https://github.com/whitecatboard/Lua-RTOS-ESP32/issues/405#issuecomment-1098922556_

**Comment by the0ne** [comment]
I think that's a pretty Lua specific question, maybe best to ask in a forum regarding Lua itself.

**Comment by progerstar** [comment]
Generic lua works.
Tests from ./components/fs_images/tests/tests - don't.
Does your example work in your build?

**Comment by progerstar** [comment]
my mistake

**Comment by the0ne** [comment]
Ok.
What was the cause of the issue?
