### ISSUE TITLE
OK to remove HOST_PLATFORM from env file?

### ISSUE THREAD

**Issue by jcwren** [whitecatboard/Lua-RTOS-ESP32#44]
While setting up the development environment on a Windows machine, I was looking for what to set HOST_PLATFORM to (default is macosx). After checking the Lua-RTOS-ESP32, esp-idf, and xtensa-esp32-elf trees, I cannot find any reference to it being used.

If you see no issue with this, I will submit a pull request to remove it from env and README.md.

**Comment by thunderWhitecat** [comment]
Yes, it can be removed.
