### ISSUE TITLE
LoRaWAN fcnt reset after sleep

### ISSUE THREAD

**Issue by webfrank** [whitecatboard/Lua-RTOS-ESP32#55]
I made a simple script which sends the temperature out on LoRa and sleeps for 60 seconds with os.sleep(60). After sleep the board reset (Ok) but the new packet has always fcnt=1. I could disable fcnt strict check but I would expect fcnt saved on flash and retained after sleep.

**Comment by thunderWhitecat** [comment]
We close this issue. Please reopen it if necessary.
