### ISSUE TITLE
Improved TLS support for MQTT

### ISSUE THREAD

**Issue by ela2342** [whitecatboard/Lua-RTOS-ESP32#62]
I've recently been trying to use the TLS support in MQTT.

First the good news: the stack is able to establish a secure connection to my MQTT broker (mosquitto in this case), and to send messages.

Bad news: I get this error message:

`SSLSocket error WANT_READ/WANT_WRITE in SSL_read - getch for socket 16`

Also, I'd like to suggest support for server certificate validation, as well as client certificates, as a feature request.

**Comment by the0ne** [comment]
hi @andreas23 
will be happy to test your pull request.

**Comment by ela2342** [comment]
Looked into it. So support for certificate validation was removed here:

https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/bfaca2f6c818fe54673da22c07d6b9c7fc659061#diff-35574f529fe1fc96033be874bd6aa50dL510

Because the openssl wrapper for mbedtls, which is part of esp-idf, doesn't support the functionality. Right?

**Comment by the0ne** [comment]
True.
Should be possible to add (non-wrapper) mbedtls calls to add the verification.

**Comment by the0ne** [comment]
@andreas23 do you need advice to implement the required changes?

**Comment by the0ne** [comment]
implemented in #86 and #87 
@andreas23 please test to help close this issue

**Comment by thunderWhitecat** [comment]
@andreas23, @the0ne,

For us this issue can be closed. Our tests about TLS support are satisfactory.

**Comment by the0ne** [comment]
@jolivepetrus I think the issue can be closed as TLS and server cert verification works
