### ISSUE TITLE
drivers/spi.c  doesn't allow a mode value of 3

### ISSUE THREAD

**Issue by tcoram** [whitecatboard/Lua-RTOS-ESP32#67]
When calling (in Lua) spi.attach(), a mode of 3 is rejected.

In the C function spi_setup() you return an error if mode is >= 3 (CKP=1, CPHA = 1)

Also, the (wiki) documentation for spi.attach() doesn't match the example (and the ordering of parameters are incorrect).

**Comment by thunderWhitecat** [comment]
@tcoram, thanks for report this.

This is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/457996d4c6f59871333b8da73c552601726f2b38.
Wiki updated.
