### ISSUE TITLE
Lua SPI id names for SPI2 and SPI3 are not consistent with SPI0, SPI1 naming

### ISSUE THREAD

**Issue by tcoram** [whitecatboard/Lua-RTOS-ESP32#68]
In the Lua "spi" table:

SPI0	0
SPI1	1
SPI2(HSPI)	2
SPI3(VSPI)	3

Maybe it just needs to be documented as such?

**Comment by thunderWhitecat** [comment]
@tcoram, thanks for report this.

This was an old page and has been removed. For know the pins assigned to spi you can use the spi.pins() function.
