### ISSUE TITLE
Mismatch between esp-idf documentation and code assumptions for ADC.

### ISSUE THREAD

**Issue by ela2342** [whitecatboard/Lua-RTOS-ESP32#73]
According to https://esp-idf.readthedocs.io/en/v2.0/api/peripherals/adc.html the reference voltage for 11db attenuation is 3.9V. The internal ADC code however assumes a reference value of 3.3V for this value.

**Comment by thunderWhitecat** [comment]
@andreas23, thanks for report this.

This is done in commit https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/3d807b8856acf2d0ef026772b44e4910f891967b.

We have waited months and months to get a better idea of how the ADC works in ESP32. It seems that esp-idf commit https://github.com/espressif/esp-idf/commit/a1b5813049decf00c0c24beb5108bc4a5a01d201 resolve in part the ADC non linearity problems.

**Comment by ela2342** [comment]
Thanks!
