### ISSUE TITLE
Feature request: lora component as a git submodule

### ISSUE THREAD

**Issue by Smeedy** [whitecatboard/Lua-RTOS-ESP32#88]
Not sure if this is the right place to ask, but here goes. I'm looking for a lorawan ESP-IDF implementation of the LMIC and this looks the best candidate. Could the ESP-IDF lora component be converted to a generic git submode so more C/C++ projects could use this as a drop-in?

Thx, Martijn

**Comment by the0ne** [comment]
related to #18
