### ISSUE TITLE
uart attach freezes chip

### ISSUE THREAD

**Issue by gjongenelen** [whitecatboard/Lua-RTOS-ESP32#89]
When I use uart.attach, the terminal crashes (screen). In a previous version this wasn't a issue. Could this be because of a change in LuaRTOS?

**Comment by thunderWhitecat** [comment]
Have you a sample code that causes this issue?

**Comment by gjongenelen** [comment]
I'm on software version: 3ad08da4a0db69f8cefc74eff2cb4f9b0fdee392 (also tested on: 3ef7e989d6450fe31eb276bb2f770ae0052a59bd)

Entering the following command crashes the terminal connection:

```
uart.setpins(uart.UART2, pio.GPIO2, pio.GPIO4)
uart.attach(uart.UART2, 9600, 8, uart.PARNONE, uart.STOP1)
```

Using different UARTS or pins doesn't work. As soon as I run uart.attach, it crashes after entering 1 character in terminal (**screen /dev/ttyUSB0 115200**)

Edit: So, after updating esp-idf and luartos and making, it has the same behavior, but it shows the following message "**(33) boot: PRO CPU has been reset by WDT.**"

<img width="1031" alt="screen shot 2017-10-09 at 4 19 56 pm" src="https://user-images.githubusercontent.com/5789343/31342821-25341da8-ad0e-11e7-9d4d-03b916a8a48c.png">

**Comment by thunderWhitecat** [comment]
Thanks for report this issue. Something has changed in esp-idf related to the UART.

Please, try with this commit. It should resolve this issue:

https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/d7341ad85cb58811604855081f34cdc0f5baf13f

**Comment by gjongenelen** [comment]
Thanks, that fixed it. Is the problem with the weird indents related to this? Because this keeps occurring. (also fails to upload files via wcc)
![screen shot 2017-10-10 at 8 57 34 am](https://user-images.githubusercontent.com/5789343/31373118-143f2caa-ad99-11e7-81c8-ed8d539371c0.png)

**Comment by thunderWhitecat** [comment]
You need to change 2 setting2 in your kconfig

Follow this steps:

* From the command line: make menuconfig
* Change this settings
Component config -> ESP32-specific -> Line ending for UART output: set to LF
Component config -> ESP32-specific -> Line ending for UART input: set to LF
* Exit and save changes.
* make flash

**Comment by gjongenelen** [comment]
Thanks!
