### ISSUE TITLE
minor issues

### ISSUE THREAD

**Issue by loboris** [whitecatboard/Lua-RTOS-ESP32#9]
case sensivity issue (FreeRTOS.h) in _components/lua_rtos/sys/semaphore.h_

Makefile -> restore-idf -> @rm $(IDF_PATH)/components/lua_rtos
error on first build, when symbolic link _$(IDF_PATH)/components/lua_rtos does not exist_

GPIO for activity led is configured in _components/lua_rtos/Makefile.projbuild_. Probably should be better if it is configurable with menuconfig (e.g., I'm using _SparkFun ESP32 Thing_ board which has the led on GPIO5)

**Comment by thunderWhitecat** [comment]
Thanks for report this. This is solved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/e01950decaa05cb5ce69f07ab2db9d8a0431835d.

**Comment by loboris** [comment]
Thanks and congratulations on the great work...
