### ISSUE TITLE
os.rename works incorrectly in some situations

### ISSUE THREAD

**Issue by bhgv** [whitecatboard/Lua-RTOS-ESP32#91]
let we have next files:

t
t.t

if we try to rename "t" like

os.rename("t", "tt")

it will work wrong.

i will send a patch soon

**Comment by bhgv** [comment]
i've sent the pr with my solution. but for some reason github added to it changes from other branch.

the solution is 
here https://github.com/bhgv/Lua-RTOS-ESP32/blob/4PR/components/lua_rtos/vfs/spiffs.c
in the function vfs_spiffs_rename . maybe this will be easier

**Comment by thunderWhitecat** [comment]
Resolved in https://github.com/whitecatboard/Lua-RTOS-ESP32/commit/a6263e776584a15047bb13149f56940b45f3bc82.
