### ISSUE TITLE
Parameters to pwm attach

### ISSUE THREAD

**Issue by pocampov** [whitecatboard/Lua-RTOS-ESP32#98]
Hello, about de pwm, in the wiki it say:
device = pwm.attach(pin, frequency, initial duty)
3 parameters, but in the examples in the same page:
device = pwm.attach(pwm.PWM0, 0, pio.GPIO16, 10000, 0.5)
5 parameters. What is the right?

**Comment by thunderWhitecat** [comment]
Hi @pocampov,

Thanks for report this. Wiki examples have been updated, the correct syntax is:

device = pwm.attach(pin, frequency, initial duty)
